/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type CreateFoodLogBody,
    CreateFoodLogBodyFromJSON,
    CreateFoodLogBodyToJSON,
} from '../models/CreateFoodLogBody.js';
import {
    type DeleteFoodLogResponse,
    DeleteFoodLogResponseFromJSON,
    DeleteFoodLogResponseToJSON,
} from '../models/DeleteFoodLogResponse.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type FoodLog,
    FoodLogFromJSON,
    FoodLogToJSON,
} from '../models/FoodLog.js';
import {
    type ListFoodLogsResponse,
    ListFoodLogsResponseFromJSON,
    ListFoodLogsResponseToJSON,
} from '../models/ListFoodLogsResponse.js';
import {
    type UpdateFoodLogBody,
    UpdateFoodLogBodyFromJSON,
    UpdateFoodLogBodyToJSON,
} from '../models/UpdateFoodLogBody.js';

export interface CreateFoodLogRequest {
    xEndUserId: string;
    createFoodLogBody: CreateFoodLogBody;
    xEndUserTimezone?: string;
}

export interface DeleteFoodLogRequest {
    xEndUserId: string;
    logId: string;
    xEndUserTimezone?: string;
}

export interface ListFoodLogsRequest {
    xEndUserId: string;
    start: Date;
    end: Date;
    xEndUserTimezone?: string;
}

export interface UpdateFoodLogRequest {
    xEndUserId: string;
    logId: string;
    updateFoodLogBody: UpdateFoodLogBody;
    xEndUserTimezone?: string;
}

/**
 *
 */
export class FoodLogsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createFoodLog without sending the request
     */
    async createFoodLogRequestOpts(requestParameters: CreateFoodLogRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xEndUserId'] == null) {
            throw new runtime.RequiredError(
                'xEndUserId',
                'Required parameter "xEndUserId" was null or undefined when calling createFoodLog().'
            );
        }

        if (requestParameters['createFoodLogBody'] == null) {
            throw new runtime.RequiredError(
                'createFoodLogBody',
                'Required parameter "createFoodLogBody" was null or undefined when calling createFoodLog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (requestParameters['xEndUserTimezone'] != null) {
            headerParameters['x-end-user-timezone'] = String(requestParameters['xEndUserTimezone']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/food-logs`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFoodLogBodyToJSON(requestParameters['createFoodLogBody']),
        };
    }

    /**
     * Creates a food log from food + serving ids (from search, scan, or detection results). The response echoes the log hydrated with full nutrition — save its `id` to update or delete the log. Not idempotent: verify with the list endpoint before retrying a timed-out create.
     * Log foods for a user
     */
    async createFoodLogRaw(requestParameters: CreateFoodLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoodLog>> {
        const requestOptions = await this.createFoodLogRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoodLogFromJSON(jsonValue));
    }

    /**
     * Creates a food log from food + serving ids (from search, scan, or detection results). The response echoes the log hydrated with full nutrition — save its `id` to update or delete the log. Not idempotent: verify with the list endpoint before retrying a timed-out create.
     * Log foods for a user
     */
    async createFoodLog(requestParameters: CreateFoodLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoodLog> {
        const response = await this.createFoodLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteFoodLog without sending the request
     */
    async deleteFoodLogRequestOpts(requestParameters: DeleteFoodLogRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xEndUserId'] == null) {
            throw new runtime.RequiredError(
                'xEndUserId',
                'Required parameter "xEndUserId" was null or undefined when calling deleteFoodLog().'
            );
        }

        if (requestParameters['logId'] == null) {
            throw new runtime.RequiredError(
                'logId',
                'Required parameter "logId" was null or undefined when calling deleteFoodLog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (requestParameters['xEndUserTimezone'] != null) {
            headerParameters['x-end-user-timezone'] = String(requestParameters['xEndUserTimezone']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/food-logs/{log_id}`;
        urlPath = urlPath.replace('{log_id}', encodeURIComponent(String(requestParameters['logId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Idempotent: deleting an unknown or already-deleted log returns the same success response, so it is safe to retry.
     * Delete a food log
     */
    async deleteFoodLogRaw(requestParameters: DeleteFoodLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteFoodLogResponse>> {
        const requestOptions = await this.deleteFoodLogRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteFoodLogResponseFromJSON(jsonValue));
    }

    /**
     * Idempotent: deleting an unknown or already-deleted log returns the same success response, so it is safe to retry.
     * Delete a food log
     */
    async deleteFoodLog(requestParameters: DeleteFoodLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteFoodLogResponse> {
        const response = await this.deleteFoodLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFoodLogs without sending the request
     */
    async listFoodLogsRequestOpts(requestParameters: ListFoodLogsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xEndUserId'] == null) {
            throw new runtime.RequiredError(
                'xEndUserId',
                'Required parameter "xEndUserId" was null or undefined when calling listFoodLogs().'
            );
        }

        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling listFoodLogs().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling listFoodLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (requestParameters['xEndUserTimezone'] != null) {
            headerParameters['x-end-user-timezone'] = String(requestParameters['xEndUserTimezone']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/food-logs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the logs between `start` and `end` (both inclusive UTC calendar days), ordered by timestamp. An empty list is a valid result.
     * List a user\'s food logs in a date range
     */
    async listFoodLogsRaw(requestParameters: ListFoodLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFoodLogsResponse>> {
        const requestOptions = await this.listFoodLogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFoodLogsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the logs between `start` and `end` (both inclusive UTC calendar days), ordered by timestamp. An empty list is a valid result.
     * List a user\'s food logs in a date range
     */
    async listFoodLogs(requestParameters: ListFoodLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFoodLogsResponse> {
        const response = await this.listFoodLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateFoodLog without sending the request
     */
    async updateFoodLogRequestOpts(requestParameters: UpdateFoodLogRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xEndUserId'] == null) {
            throw new runtime.RequiredError(
                'xEndUserId',
                'Required parameter "xEndUserId" was null or undefined when calling updateFoodLog().'
            );
        }

        if (requestParameters['logId'] == null) {
            throw new runtime.RequiredError(
                'logId',
                'Required parameter "logId" was null or undefined when calling updateFoodLog().'
            );
        }

        if (requestParameters['updateFoodLogBody'] == null) {
            throw new runtime.RequiredError(
                'updateFoodLogBody',
                'Required parameter "updateFoodLogBody" was null or undefined when calling updateFoodLog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (requestParameters['xEndUserTimezone'] != null) {
            headerParameters['x-end-user-timezone'] = String(requestParameters['xEndUserTimezone']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/food-logs/{log_id}`;
        urlPath = urlPath.replace('{log_id}', encodeURIComponent(String(requestParameters['logId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFoodLogBodyToJSON(requestParameters['updateFoodLogBody']),
        };
    }

    /**
     * Replaces any subset of the log: `foods`, `timestamp_utc`, `name`.
     * Update a food log
     */
    async updateFoodLogRaw(requestParameters: UpdateFoodLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoodLog>> {
        const requestOptions = await this.updateFoodLogRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoodLogFromJSON(jsonValue));
    }

    /**
     * Replaces any subset of the log: `foods`, `timestamp_utc`, `name`.
     * Update a food log
     */
    async updateFoodLog(requestParameters: UpdateFoodLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoodLog> {
        const response = await this.updateFoodLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
