/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type FoodCategory,
    FoodCategoryFromJSON,
    FoodCategoryToJSON,
} from '../models/FoodCategory.js';
import {
    type FoodSearchResults,
    FoodSearchResultsFromJSON,
    FoodSearchResultsToJSON,
} from '../models/FoodSearchResults.js';
import {
    type SearchFoodsByNaturalLanguageResponse,
    SearchFoodsByNaturalLanguageResponseFromJSON,
    SearchFoodsByNaturalLanguageResponseToJSON,
} from '../models/SearchFoodsByNaturalLanguageResponse.js';
import {
    type SuggestFoodAlternativesBody,
    SuggestFoodAlternativesBodyFromJSON,
    SuggestFoodAlternativesBodyToJSON,
} from '../models/SuggestFoodAlternativesBody.js';
import {
    type SuggestFoodAlternativesResponse,
    SuggestFoodAlternativesResponseFromJSON,
    SuggestFoodAlternativesResponseToJSON,
} from '../models/SuggestFoodAlternativesResponse.js';

export interface LookupFoodByBarcodeRequest {
    upc: string;
    xEndUserId?: string;
}

export interface SearchFoodsRequest {
    query: string;
    xEndUserId?: string;
    category?: FoodCategory;
    limit?: number;
}

export interface SearchFoodsByNaturalLanguageRequest {
    query: string;
    xEndUserId?: string;
}

export interface SuggestFoodAlternativesRequest {
    foodId: number;
    suggestFoodAlternativesBody: SuggestFoodAlternativesBody;
    xEndUserId?: string;
}

/**
 *
 */
export class FoodsApi extends runtime.BaseAPI {

    /**
     * Creates request options for lookupFoodByBarcode without sending the request
     */
    async lookupFoodByBarcodeRequestOpts(requestParameters: LookupFoodByBarcodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['upc'] == null) {
            throw new runtime.RequiredError(
                'upc',
                'Required parameter "upc" was null or undefined when calling lookupFoodByBarcode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/foods/barcode/{upc}`;
        urlPath = urlPath.replace('{upc}', encodeURIComponent(String(requestParameters['upc'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Exact lookup of a food by its barcode. For free-text search, use `GET /v1.2/foods/search` instead.
     * Look up a food by barcode
     */
    async lookupFoodByBarcodeRaw(requestParameters: LookupFoodByBarcodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoodSearchResults>> {
        const requestOptions = await this.lookupFoodByBarcodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoodSearchResultsFromJSON(jsonValue));
    }

    /**
     * Exact lookup of a food by its barcode. For free-text search, use `GET /v1.2/foods/search` instead.
     * Look up a food by barcode
     */
    async lookupFoodByBarcode(requestParameters: LookupFoodByBarcodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoodSearchResults> {
        const response = await this.lookupFoodByBarcodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchFoods without sending the request
     */
    async searchFoodsRequestOpts(requestParameters: SearchFoodsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchFoods().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/foods/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Full-text search over the January food database, returning up to 40 ranked matches. To look up a scanned barcode, use `GET /v1.2/foods/barcode/{upc}` instead.
     * Search foods by name
     */
    async searchFoodsRaw(requestParameters: SearchFoodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoodSearchResults>> {
        const requestOptions = await this.searchFoodsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoodSearchResultsFromJSON(jsonValue));
    }

    /**
     * Full-text search over the January food database, returning up to 40 ranked matches. To look up a scanned barcode, use `GET /v1.2/foods/barcode/{upc}` instead.
     * Search foods by name
     */
    async searchFoods(requestParameters: SearchFoodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoodSearchResults> {
        const response = await this.searchFoodsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchFoodsByNaturalLanguage without sending the request
     */
    async searchFoodsByNaturalLanguageRequestOpts(requestParameters: SearchFoodsByNaturalLanguageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchFoodsByNaturalLanguage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/foods/search/nlp`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Natural-language food search: parses free text like \"a bowl of oatmeal with honey\" into detected foods with quantities and nutrition — the text counterpart of meal-scan. For keyword search over the food database, use `GET /v1.2/foods/search`.
     * Parse a meal description into foods
     */
    async searchFoodsByNaturalLanguageRaw(requestParameters: SearchFoodsByNaturalLanguageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchFoodsByNaturalLanguageResponse>> {
        const requestOptions = await this.searchFoodsByNaturalLanguageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchFoodsByNaturalLanguageResponseFromJSON(jsonValue));
    }

    /**
     * Natural-language food search: parses free text like \"a bowl of oatmeal with honey\" into detected foods with quantities and nutrition — the text counterpart of meal-scan. For keyword search over the food database, use `GET /v1.2/foods/search`.
     * Parse a meal description into foods
     */
    async searchFoodsByNaturalLanguage(requestParameters: SearchFoodsByNaturalLanguageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchFoodsByNaturalLanguageResponse> {
        const response = await this.searchFoodsByNaturalLanguageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for suggestFoodAlternatives without sending the request
     */
    async suggestFoodAlternativesRequestOpts(requestParameters: SuggestFoodAlternativesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['foodId'] == null) {
            throw new runtime.RequiredError(
                'foodId',
                'Required parameter "foodId" was null or undefined when calling suggestFoodAlternatives().'
            );
        }

        if (requestParameters['suggestFoodAlternativesBody'] == null) {
            throw new runtime.RequiredError(
                'suggestFoodAlternativesBody',
                'Required parameter "suggestFoodAlternativesBody" was null or undefined when calling suggestFoodAlternatives().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/foods/{food_id}/alternatives`;
        urlPath = urlPath.replace('{food_id}', encodeURIComponent(String(requestParameters['foodId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SuggestFoodAlternativesBodyToJSON(requestParameters['suggestFoodAlternativesBody']),
        };
    }

    /**
     * Returns healthier alternatives for a food, honoring the given dietary restrictions and preferences. Send `[\"None\"]` (not an empty array) to opt out of either. An empty `alternatives` result is valid — no suitable alternatives were found.
     * Suggest healthier alternatives for a food
     */
    async suggestFoodAlternativesRaw(requestParameters: SuggestFoodAlternativesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuggestFoodAlternativesResponse>> {
        const requestOptions = await this.suggestFoodAlternativesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuggestFoodAlternativesResponseFromJSON(jsonValue));
    }

    /**
     * Returns healthier alternatives for a food, honoring the given dietary restrictions and preferences. Send `[\"None\"]` (not an empty array) to opt out of either. An empty `alternatives` result is valid — no suitable alternatives were found.
     * Suggest healthier alternatives for a food
     */
    async suggestFoodAlternatives(requestParameters: SuggestFoodAlternativesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuggestFoodAlternativesResponse> {
        const response = await this.suggestFoodAlternativesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
