/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type GlucosePrediction,
    GlucosePredictionFromJSON,
    GlucosePredictionToJSON,
} from '../models/GlucosePrediction.js';
import {
    type PredictGlucoseBody,
    PredictGlucoseBodyFromJSON,
    PredictGlucoseBodyToJSON,
} from '../models/PredictGlucoseBody.js';

export interface PredictGlucoseRequest {
    predictGlucoseBody: PredictGlucoseBody;
    xEndUserId?: string;
    xEndUserTimezone?: string;
}

/**
 *
 */
export class GlucoseApi extends runtime.BaseAPI {

    /**
     * Creates request options for predictGlucose without sending the request
     */
    async predictGlucoseRequestOpts(requestParameters: PredictGlucoseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['predictGlucoseBody'] == null) {
            throw new runtime.RequiredError(
                'predictGlucoseBody',
                'Required parameter "predictGlucoseBody" was null or undefined when calling predictGlucose().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (requestParameters['xEndUserTimezone'] != null) {
            headerParameters['x-end-user-timezone'] = String(requestParameters['xEndUserTimezone']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/glucose/predictions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PredictGlucoseBodyToJSON(requestParameters['predictGlucoseBody']),
        };
    }

    /**
     * Predicts the glucose curve a meal will produce for the given profile. Optionally personalize by sending cgm_data with the consumed_foods eaten during it (both together; the upstream needs at least five complete days of paired history). Without x-end-user-id, the partner itself is the acting user.
     * Predict the glucose response to a meal
     */
    async predictGlucoseRaw(requestParameters: PredictGlucoseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GlucosePrediction>> {
        const requestOptions = await this.predictGlucoseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GlucosePredictionFromJSON(jsonValue));
    }

    /**
     * Predicts the glucose curve a meal will produce for the given profile. Optionally personalize by sending cgm_data with the consumed_foods eaten during it (both together; the upstream needs at least five complete days of paired history). Without x-end-user-id, the partner itself is the acting user.
     * Predict the glucose response to a meal
     */
    async predictGlucose(requestParameters: PredictGlucoseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GlucosePrediction> {
        const response = await this.predictGlucoseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
