/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type SearchRestaurantMenuItemsResponse,
    SearchRestaurantMenuItemsResponseFromJSON,
    SearchRestaurantMenuItemsResponseToJSON,
} from '../models/SearchRestaurantMenuItemsResponse.js';
import {
    type SearchRestaurantsResponse,
    SearchRestaurantsResponseFromJSON,
    SearchRestaurantsResponseToJSON,
} from '../models/SearchRestaurantsResponse.js';

export interface SearchRestaurantMenuItemsRequest {
    query: string;
    latitude: number;
    longitude: number;
    xEndUserId?: string;
    radius?: number;
    limit?: number;
}

export interface SearchRestaurantsRequest {
    query: string;
    latitude: number;
    longitude: number;
    xEndUserId?: string;
    radius?: number;
    limit?: number;
}

/**
 *
 */
export class RestaurantsApi extends runtime.BaseAPI {

    /**
     * Creates request options for searchRestaurantMenuItems without sending the request
     */
    async searchRestaurantMenuItemsRequestOpts(requestParameters: SearchRestaurantMenuItemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchRestaurantMenuItems().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling searchRestaurantMenuItems().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling searchRestaurantMenuItems().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['radius'] != null) {
            queryParameters['radius'] = requestParameters['radius'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/restaurants/menu/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search dishes across restaurants near (`latitude`, `longitude`). Returns menu items with their nutrition values. `radius` and result distances are in meters, e.g. radius=5000 for 5 kilometers.
     * Search menu items near a location
     */
    async searchRestaurantMenuItemsRaw(requestParameters: SearchRestaurantMenuItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchRestaurantMenuItemsResponse>> {
        const requestOptions = await this.searchRestaurantMenuItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchRestaurantMenuItemsResponseFromJSON(jsonValue));
    }

    /**
     * Search dishes across restaurants near (`latitude`, `longitude`). Returns menu items with their nutrition values. `radius` and result distances are in meters, e.g. radius=5000 for 5 kilometers.
     * Search menu items near a location
     */
    async searchRestaurantMenuItems(requestParameters: SearchRestaurantMenuItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchRestaurantMenuItemsResponse> {
        const response = await this.searchRestaurantMenuItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchRestaurants without sending the request
     */
    async searchRestaurantsRequestOpts(requestParameters: SearchRestaurantsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchRestaurants().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling searchRestaurants().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling searchRestaurants().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['radius'] != null) {
            queryParameters['radius'] = requestParameters['radius'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/restaurants/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search restaurants matching `query` around (`latitude`, `longitude`), ranked by proximity. When the name matches no restaurant, results may be menu items (`type: \"menu_item\"`). `radius` and result distances are in meters.
     * Search restaurants near a location
     */
    async searchRestaurantsRaw(requestParameters: SearchRestaurantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchRestaurantsResponse>> {
        const requestOptions = await this.searchRestaurantsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchRestaurantsResponseFromJSON(jsonValue));
    }

    /**
     * Search restaurants matching `query` around (`latitude`, `longitude`), ranked by proximity. When the name matches no restaurant, results may be menu items (`type: \"menu_item\"`). `radius` and result distances are in meters.
     * Search restaurants near a location
     */
    async searchRestaurants(requestParameters: SearchRestaurantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchRestaurantsResponse> {
        const response = await this.searchRestaurantsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
