/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type SearchRestaurantMenuItemsResponse,
    SearchRestaurantMenuItemsResponseFromJSON,
    SearchRestaurantMenuItemsResponseToJSON,
} from '../models/SearchRestaurantMenuItemsResponse.js';
import {
    type SearchRestaurantsResponse,
    SearchRestaurantsResponseFromJSON,
    SearchRestaurantsResponseToJSON,
} from '../models/SearchRestaurantsResponse.js';

export interface SearchRestaurantMenuItemsRequest {
    query: string;
    latitude: number;
    longitude: number;
    xEndUserId?: string;
    radius?: number;
    limit?: number;
}

export interface SearchRestaurantsRequest {
    query: string;
    latitude: number;
    longitude: number;
    xEndUserId?: string;
    radius?: number;
    limit?: number;
}

/**
 *
 */
export class RestaurantsApi extends runtime.BaseAPI {

    /**
     * Creates request options for searchRestaurantMenuItems without sending the request
     */
    async searchRestaurantMenuItemsRequestOpts(requestParameters: SearchRestaurantMenuItemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchRestaurantMenuItems().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling searchRestaurantMenuItems().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling searchRestaurantMenuItems().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['radius'] != null) {
            queryParameters['radius'] = requestParameters['radius'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/restaurants/menu-items`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search dishes across restaurants near (`latitude`, `longitude`). Returns menu items with their nutrition values. `radius` and result distances are in meters, e.g. radius=5000 for 5 kilometers.
     * Search menu items near a location
     */
    async searchRestaurantMenuItemsRaw(requestParameters: SearchRestaurantMenuItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchRestaurantMenuItemsResponse>> {
        const requestOptions = await this.searchRestaurantMenuItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchRestaurantMenuItemsResponseFromJSON(jsonValue));
    }

    /**
     * Search dishes across restaurants near (`latitude`, `longitude`). Returns menu items with their nutrition values. `radius` and result distances are in meters, e.g. radius=5000 for 5 kilometers.
     * Search menu items near a location
     */
    async searchRestaurantMenuItems(requestParameters: SearchRestaurantMenuItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchRestaurantMenuItemsResponse> {
        const response = await this.searchRestaurantMenuItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchRestaurants without sending the request
     */
    async searchRestaurantsRequestOpts(requestParameters: SearchRestaurantsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchRestaurants().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling searchRestaurants().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling searchRestaurants().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['radius'] != null) {
            queryParameters['radius'] = requestParameters['radius'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xEndUserId'] != null) {
            headerParameters['x-end-user-id'] = String(requestParameters['xEndUserId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1.2/restaurants`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search restaurants matching `query` around (`latitude`, `longitude`), ranked by proximity. When the name matches no restaurant, results may be menu items (`type: \"menu_item\"`). `radius` and result distances are in meters.
     * Search restaurants near a location
     */
    async searchRestaurantsRaw(requestParameters: SearchRestaurantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchRestaurantsResponse>> {
        const requestOptions = await this.searchRestaurantsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchRestaurantsResponseFromJSON(jsonValue));
    }

    /**
     * Search restaurants matching `query` around (`latitude`, `longitude`), ranked by proximity. When the name matches no restaurant, results may be menu items (`type: \"menu_item\"`). `radius` and result distances are in meters.
     * Search restaurants near a location
     */
    async searchRestaurants(requestParameters: SearchRestaurantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchRestaurantsResponse> {
        const response = await this.searchRestaurantsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
