/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodLogsRouteImport } from './routes/food-logs'
import { Route as GlucoseRouteImport } from './routes/glucose'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodLogsRoute = FoodLogsRouteImport.update({
  id: '/food-logs',
  path: '/food-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const GlucoseRoute = GlucoseRouteImport.update({
  id: '/glucose',
  path: '/glucose',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/food-logs': typeof FoodLogsRoute
  '/glucose': typeof GlucoseRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/food-logs': typeof FoodLogsRoute
  '/glucose': typeof GlucoseRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/food-logs': typeof FoodLogsRoute
  '/glucose': typeof GlucoseRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/food-logs' | '/glucose' | '/scan' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/food-logs' | '/glucose' | '/scan' | '/search'
  id: '__root__' | '/' | '/food-logs' | '/glucose' | '/scan' | '/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodLogsRoute: typeof FoodLogsRoute
  GlucoseRoute: typeof GlucoseRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-logs': {
      id: '/food-logs'
      path: '/food-logs'
      fullPath: '/food-logs'
      preLoaderRoute: typeof FoodLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glucose': {
      id: '/glucose'
      path: '/glucose'
      fullPath: '/glucose'
      preLoaderRoute: typeof GlucoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodLogsRoute: FoodLogsRoute,
  GlucoseRoute: GlucoseRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
