/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const ActivityLevel = {
    sedentary: 'sedentary',
    lightlyActive: 'lightly_active',
    moderatelyActive: 'moderately_active',
    veryActive: 'very_active',
    unknownDefaultOpenApi: '11184809'
} as const;
export type ActivityLevel = typeof ActivityLevel[keyof typeof ActivityLevel];


export function instanceOfActivityLevel(value: any): boolean {
    for (const key in ActivityLevel) {
        if (Object.prototype.hasOwnProperty.call(ActivityLevel, key)) {
            if (ActivityLevel[key as keyof typeof ActivityLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActivityLevelFromJSON(json: any): ActivityLevel {
    return ActivityLevelFromJSONTyped(json, false);
}

export function ActivityLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLevel {
    return json as ActivityLevel;
}

export function ActivityLevelToJSON(value?: ActivityLevel | null): any {
    return value as any;
}

export function ActivityLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): ActivityLevel {
    return value as ActivityLevel;
}
