/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface CgmReading
 */
export interface CgmReading {
    /**
     *
     * @type {string}
     * @memberof CgmReading
     */
    timestamp: string;
    /**
     * mg/dL. At most one reading per 15-minute window.
     * @type {number}
     * @memberof CgmReading
     */
    value: number;
}

/**
 * Check if a given object implements the CgmReading interface.
 */
export function instanceOfCgmReading(value: object): value is CgmReading {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CgmReadingFromJSON(json: any): CgmReading {
    return CgmReadingFromJSONTyped(json, false);
}

export function CgmReadingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CgmReading {
    if (json == null) {
        return json;
    }
    return {

        'timestamp': json['timestamp'],
        'value': json['value'],
    };
}

export function CgmReadingToJSON(json: any): CgmReading {
    return CgmReadingToJSONTyped(json, false);
}

export function CgmReadingToJSONTyped(value?: CgmReading | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}
