/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NutrientAmount } from './NutrientAmount.js';
import {
    NutrientAmountFromJSON,
    NutrientAmountFromJSONTyped,
    NutrientAmountToJSON,
    NutrientAmountToJSONTyped,
} from './NutrientAmount.js';

/**
 *
 * @export
 * @interface CompleteScanNutritionFacts
 */
export interface CompleteScanNutritionFacts {
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    calories?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    protein?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    carbohydrates?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    netCarbohydrates?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    totalFat?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    saturatedFat?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    fiber?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    totalSugars?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    addedSugars?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof CompleteScanNutritionFacts
     */
    sodium?: NutrientAmount;
}

/**
 * Check if a given object implements the CompleteScanNutritionFacts interface.
 */
export function instanceOfCompleteScanNutritionFacts(value: object): value is CompleteScanNutritionFacts {
    return true;
}

export function CompleteScanNutritionFactsFromJSON(json: any): CompleteScanNutritionFacts {
    return CompleteScanNutritionFactsFromJSONTyped(json, false);
}

export function CompleteScanNutritionFactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteScanNutritionFacts {
    if (json == null) {
        return json;
    }
    return {

        'calories': json['calories'] == null ? undefined : NutrientAmountFromJSON(json['calories']),
        'protein': json['protein'] == null ? undefined : NutrientAmountFromJSON(json['protein']),
        'carbohydrates': json['carbohydrates'] == null ? undefined : NutrientAmountFromJSON(json['carbohydrates']),
        'netCarbohydrates': json['net_carbohydrates'] == null ? undefined : NutrientAmountFromJSON(json['net_carbohydrates']),
        'totalFat': json['total_fat'] == null ? undefined : NutrientAmountFromJSON(json['total_fat']),
        'saturatedFat': json['saturated_fat'] == null ? undefined : NutrientAmountFromJSON(json['saturated_fat']),
        'fiber': json['fiber'] == null ? undefined : NutrientAmountFromJSON(json['fiber']),
        'totalSugars': json['total_sugars'] == null ? undefined : NutrientAmountFromJSON(json['total_sugars']),
        'addedSugars': json['added_sugars'] == null ? undefined : NutrientAmountFromJSON(json['added_sugars']),
        'sodium': json['sodium'] == null ? undefined : NutrientAmountFromJSON(json['sodium']),
    };
}

export function CompleteScanNutritionFactsToJSON(json: any): CompleteScanNutritionFacts {
    return CompleteScanNutritionFactsToJSONTyped(json, false);
}

export function CompleteScanNutritionFactsToJSONTyped(value?: CompleteScanNutritionFacts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'calories': NutrientAmountToJSON(value['calories']),
        'protein': NutrientAmountToJSON(value['protein']),
        'carbohydrates': NutrientAmountToJSON(value['carbohydrates']),
        'net_carbohydrates': NutrientAmountToJSON(value['netCarbohydrates']),
        'total_fat': NutrientAmountToJSON(value['totalFat']),
        'saturated_fat': NutrientAmountToJSON(value['saturatedFat']),
        'fiber': NutrientAmountToJSON(value['fiber']),
        'total_sugars': NutrientAmountToJSON(value['totalSugars']),
        'added_sugars': NutrientAmountToJSON(value['addedSugars']),
        'sodium': NutrientAmountToJSON(value['sodium']),
    };
}
