/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConsumedHistoricalServing } from './ConsumedHistoricalServing.js';
import {
    ConsumedHistoricalServingFromJSON,
    ConsumedHistoricalServingFromJSONTyped,
    ConsumedHistoricalServingToJSON,
    ConsumedHistoricalServingToJSONTyped,
} from './ConsumedHistoricalServing.js';

/**
 *
 * @export
 * @interface ConsumedHistoricalFood
 */
export interface ConsumedHistoricalFood {
    /**
     *
     * @type {string}
     * @memberof ConsumedHistoricalFood
     */
    timestamp: string;
    /**
     * Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof ConsumedHistoricalFood
     */
    id: number;
    /**
     *
     * @type {ConsumedHistoricalServing}
     * @memberof ConsumedHistoricalFood
     */
    serving: ConsumedHistoricalServing;
}

/**
 * Check if a given object implements the ConsumedHistoricalFood interface.
 */
export function instanceOfConsumedHistoricalFood(value: object): value is ConsumedHistoricalFood {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('serving' in value) || value['serving'] === undefined) return false;
    return true;
}

export function ConsumedHistoricalFoodFromJSON(json: any): ConsumedHistoricalFood {
    return ConsumedHistoricalFoodFromJSONTyped(json, false);
}

export function ConsumedHistoricalFoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumedHistoricalFood {
    if (json == null) {
        return json;
    }
    return {

        'timestamp': json['timestamp'],
        'id': json['id'],
        'serving': ConsumedHistoricalServingFromJSON(json['serving']),
    };
}

export function ConsumedHistoricalFoodToJSON(json: any): ConsumedHistoricalFood {
    return ConsumedHistoricalFoodToJSONTyped(json, false);
}

export function ConsumedHistoricalFoodToJSONTyped(value?: ConsumedHistoricalFood | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'timestamp': value['timestamp'],
        'id': value['id'],
        'serving': ConsumedHistoricalServingToJSON(value['serving']),
    };
}
