/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface ConsumedServing
 */
export interface ConsumedServing {
    /**
     * Stable serving identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof ConsumedServing
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof ConsumedServing
     */
    quantity: number;
}

/**
 * Check if a given object implements the ConsumedServing interface.
 */
export function instanceOfConsumedServing(value: object): value is ConsumedServing {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function ConsumedServingFromJSON(json: any): ConsumedServing {
    return ConsumedServingFromJSONTyped(json, false);
}

export function ConsumedServingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumedServing {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'quantity': json['quantity'],
    };
}

export function ConsumedServingToJSON(json: any): ConsumedServing {
    return ConsumedServingToJSONTyped(json, false);
}

export function ConsumedServingToJSONTyped(value?: ConsumedServing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'quantity': value['quantity'],
    };
}
