/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodDetection } from './FoodDetection.js';
import {
    FoodDetectionFromJSON,
    FoodDetectionFromJSONTyped,
    FoodDetectionToJSON,
    FoodDetectionToJSONTyped,
} from './FoodDetection.js';

/**
 *
 * @export
 * @interface CorrectPhotoScanBody
 */
export interface CorrectPhotoScanBody {
    /**
     * The meal name from the scan, when it returned one (photo scans do; text scans don't). Defaults to 'Meal'.
     * @type {string}
     * @memberof CorrectPhotoScanBody
     */
    mealName?: string;
    /**
     * The detections array from a photo or text food scan, exactly as returned. Omitted zero-value nutrient keys are filled in automatically; each detection needs at least one serving.
     * @type {Array<FoodDetection>}
     * @memberof CorrectPhotoScanBody
     */
    detections: Array<FoodDetection>;
    /**
     * Plain-English description of what to correct.
     * @type {string}
     * @memberof CorrectPhotoScanBody
     */
    userInput: string;
}

/**
 * Check if a given object implements the CorrectPhotoScanBody interface.
 */
export function instanceOfCorrectPhotoScanBody(value: object): value is CorrectPhotoScanBody {
    if (!('detections' in value) || value['detections'] === undefined) return false;
    if ((!('userInput' in (value as Record<string, any>)) && !('user_input' in (value as Record<string, any>))) || ((value as Record<string, any>)['userInput'] === undefined && (value as Record<string, any>)['user_input'] === undefined)) return false;
    return true;
}

export function CorrectPhotoScanBodyFromJSON(json: any): CorrectPhotoScanBody {
    return CorrectPhotoScanBodyFromJSONTyped(json, false);
}

export function CorrectPhotoScanBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrectPhotoScanBody {
    if (json == null) {
        return json;
    }
    return {

        'mealName': json['meal_name'] == null ? undefined : json['meal_name'],
        'detections': ((json['detections'] as Array<any>).map(FoodDetectionFromJSON)),
        'userInput': json['user_input'],
    };
}

export function CorrectPhotoScanBodyToJSON(json: any): CorrectPhotoScanBody {
    return CorrectPhotoScanBodyToJSONTyped(json, false);
}

export function CorrectPhotoScanBodyToJSONTyped(value?: CorrectPhotoScanBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'meal_name': value['mealName'],
        'detections': ((value['detections'] as Array<any>).map(FoodDetectionToJSON)),
        'user_input': value['userInput'],
    };
}
