/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodDetection } from './FoodDetection.js';
import {
    FoodDetectionFromJSON,
    FoodDetectionFromJSONTyped,
    FoodDetectionToJSON,
    FoodDetectionToJSONTyped,
} from './FoodDetection.js';

/**
 *
 * @export
 * @interface CorrectPhotoScanBody
 */
export interface CorrectPhotoScanBody {
    /**
     * The meal name from the meal-scan response.
     * @type {string}
     * @memberof CorrectPhotoScanBody
     */
    mealName: string;
    /**
     * The detections array from the meal-scan response, exactly as returned (all ten nutrient keys, non-empty servings).
     * @type {Array<FoodDetection>}
     * @memberof CorrectPhotoScanBody
     */
    detections: Array<FoodDetection>;
    /**
     * Plain-English description of what to correct.
     * @type {string}
     * @memberof CorrectPhotoScanBody
     */
    userInput: string;
}

/**
 * Check if a given object implements the CorrectPhotoScanBody interface.
 */
export function instanceOfCorrectPhotoScanBody(value: object): value is CorrectPhotoScanBody {
    if ((!('mealName' in (value as Record<string, any>)) && !('meal_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['mealName'] === undefined && (value as Record<string, any>)['meal_name'] === undefined)) return false;
    if (!('detections' in value) || value['detections'] === undefined) return false;
    if ((!('userInput' in (value as Record<string, any>)) && !('user_input' in (value as Record<string, any>))) || ((value as Record<string, any>)['userInput'] === undefined && (value as Record<string, any>)['user_input'] === undefined)) return false;
    return true;
}

export function CorrectPhotoScanBodyFromJSON(json: any): CorrectPhotoScanBody {
    return CorrectPhotoScanBodyFromJSONTyped(json, false);
}

export function CorrectPhotoScanBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrectPhotoScanBody {
    if (json == null) {
        return json;
    }
    return {

        'mealName': json['meal_name'],
        'detections': ((json['detections'] as Array<any>).map(FoodDetectionFromJSON)),
        'userInput': json['user_input'],
    };
}

export function CorrectPhotoScanBodyToJSON(json: any): CorrectPhotoScanBody {
    return CorrectPhotoScanBodyToJSONTyped(json, false);
}

export function CorrectPhotoScanBodyToJSONTyped(value?: CorrectPhotoScanBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'meal_name': value['mealName'],
        'detections': ((value['detections'] as Array<any>).map(FoodDetectionToJSON)),
        'user_input': value['userInput'],
    };
}
