/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodLogInputFood } from './FoodLogInputFood.js';
import {
    FoodLogInputFoodFromJSON,
    FoodLogInputFoodFromJSONTyped,
    FoodLogInputFoodToJSON,
    FoodLogInputFoodToJSONTyped,
} from './FoodLogInputFood.js';

/**
 *
 * @export
 * @interface CreateFoodLogBody
 */
export interface CreateFoodLogBody {
    /**
     *
     * @type {Array<FoodLogInputFood>}
     * @memberof CreateFoodLogBody
     */
    foods: Array<FoodLogInputFood>;
    /**
     * UTC consumption time, ending in Z. Omitted = now.
     * @type {string}
     * @memberof CreateFoodLogBody
     */
    timestampUtc?: string;
    /**
     *
     * @type {string}
     * @memberof CreateFoodLogBody
     */
    name?: string;
}

/**
 * Check if a given object implements the CreateFoodLogBody interface.
 */
export function instanceOfCreateFoodLogBody(value: object): value is CreateFoodLogBody {
    if (!('foods' in value) || value['foods'] === undefined) return false;
    return true;
}

export function CreateFoodLogBodyFromJSON(json: any): CreateFoodLogBody {
    return CreateFoodLogBodyFromJSONTyped(json, false);
}

export function CreateFoodLogBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFoodLogBody {
    if (json == null) {
        return json;
    }
    return {

        'foods': ((json['foods'] as Array<any>).map(FoodLogInputFoodFromJSON)),
        'timestampUtc': json['timestamp_utc'] == null ? undefined : json['timestamp_utc'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateFoodLogBodyToJSON(json: any): CreateFoodLogBody {
    return CreateFoodLogBodyToJSONTyped(json, false);
}

export function CreateFoodLogBodyToJSONTyped(value?: CreateFoodLogBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'foods': ((value['foods'] as Array<any>).map(FoodLogInputFoodToJSON)),
        'timestamp_utc': value['timestampUtc'],
        'name': value['name'],
    };
}
