/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **What you can build** - **Scan food** — detect foods and nutrition from a meal photo or a plain-English description, and correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodLogInputFood } from './FoodLogInputFood.js';
import {
    FoodLogInputFoodFromJSON,
    FoodLogInputFoodFromJSONTyped,
    FoodLogInputFoodToJSON,
    FoodLogInputFoodToJSONTyped,
} from './FoodLogInputFood.js';

/**
 *
 * @export
 * @interface CreateFoodLogBody
 */
export interface CreateFoodLogBody {
    /**
     *
     * @type {Array<FoodLogInputFood>}
     * @memberof CreateFoodLogBody
     */
    foods: Array<FoodLogInputFood>;
    /**
     * When the meal was eaten — any ISO-8601 offset; stored and returned in UTC. Omitted = now.
     * @type {Date}
     * @memberof CreateFoodLogBody
     */
    timestampUtc?: Date;
    /**
     *
     * @type {string}
     * @memberof CreateFoodLogBody
     */
    name?: string;
}

/**
 * Check if a given object implements the CreateFoodLogBody interface.
 */
export function instanceOfCreateFoodLogBody(value: object): value is CreateFoodLogBody {
    if (!('foods' in value) || value['foods'] === undefined) return false;
    return true;
}

export function CreateFoodLogBodyFromJSON(json: any): CreateFoodLogBody {
    return CreateFoodLogBodyFromJSONTyped(json, false);
}

export function CreateFoodLogBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFoodLogBody {
    if (json == null) {
        return json;
    }
    return {

        'foods': ((json['foods'] as Array<any>).map(FoodLogInputFoodFromJSON)),
        'timestampUtc': json['timestamp_utc'] == null ? undefined : (new Date(json['timestamp_utc'])),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateFoodLogBodyToJSON(json: any): CreateFoodLogBody {
    return CreateFoodLogBodyToJSONTyped(json, false);
}

export function CreateFoodLogBodyToJSONTyped(value?: CreateFoodLogBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'foods': ((value['foods'] as Array<any>).map(FoodLogInputFoodToJSON)),
        'timestamp_utc': value['timestampUtc'] == null ? value['timestampUtc'] : value['timestampUtc'].toISOString(),
        'name': value['name'],
    };
}
