/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface DeleteFoodLogResponse
 */
export interface DeleteFoodLogResponse {
    /**
     * Deletion is idempotent — an unknown or already-deleted log_id returns the same response.
     * @type {string}
     * @memberof DeleteFoodLogResponse
     */
    status: string;
}

/**
 * Check if a given object implements the DeleteFoodLogResponse interface.
 */
export function instanceOfDeleteFoodLogResponse(value: object): value is DeleteFoodLogResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DeleteFoodLogResponseFromJSON(json: any): DeleteFoodLogResponse {
    return DeleteFoodLogResponseFromJSONTyped(json, false);
}

export function DeleteFoodLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteFoodLogResponse {
    if (json == null) {
        return json;
    }
    return {

        'status': json['status'],
    };
}

export function DeleteFoodLogResponseToJSON(json: any): DeleteFoodLogResponse {
    return DeleteFoodLogResponseToJSONTyped(json, false);
}

export function DeleteFoodLogResponseToJSONTyped(value?: DeleteFoodLogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'status': value['status'],
    };
}
