/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CompleteScanNutritionFacts } from './CompleteScanNutritionFacts.js';
import {
    CompleteScanNutritionFactsFromJSON,
    CompleteScanNutritionFactsFromJSONTyped,
    CompleteScanNutritionFactsToJSON,
    CompleteScanNutritionFactsToJSONTyped,
} from './CompleteScanNutritionFacts.js';
import type { DetectedServing } from './DetectedServing.js';
import {
    DetectedServingFromJSON,
    DetectedServingFromJSONTyped,
    DetectedServingToJSON,
    DetectedServingToJSONTyped,
} from './DetectedServing.js';

/**
 *
 * @export
 * @interface DetectedFood
 */
export interface DetectedFood {
    /**
     * Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof DetectedFood
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof DetectedFood
     */
    name: string;
    /**
     * Empty for generic (non-branded) foods.
     * @type {string}
     * @memberof DetectedFood
     */
    brandName?: string;
    /**
     *
     * @type {CompleteScanNutritionFacts}
     * @memberof DetectedFood
     */
    nutrients: CompleteScanNutritionFacts;
    /**
     *
     * @type {Array<DetectedServing>}
     * @memberof DetectedFood
     */
    servings?: Array<DetectedServing>;
}

/**
 * Check if a given object implements the DetectedFood interface.
 */
export function instanceOfDetectedFood(value: object): value is DetectedFood {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nutrients' in value) || value['nutrients'] === undefined) return false;
    return true;
}

export function DetectedFoodFromJSON(json: any): DetectedFood {
    return DetectedFoodFromJSONTyped(json, false);
}

export function DetectedFoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectedFood {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'nutrients': CompleteScanNutritionFactsFromJSON(json['nutrients']),
        'servings': json['servings'] == null ? undefined : ((json['servings'] as Array<any>).map(DetectedServingFromJSON)),
    };
}

export function DetectedFoodToJSON(json: any): DetectedFood {
    return DetectedFoodToJSONTyped(json, false);
}

export function DetectedFoodToJSONTyped(value?: DetectedFood | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
        'brand_name': value['brandName'],
        'nutrients': CompleteScanNutritionFactsToJSON(value['nutrients']),
        'servings': value['servings'] == null ? undefined : ((value['servings'] as Array<any>).map(DetectedServingToJSON)),
    };
}
