/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const DietRestriction = {
    none: 'None',
    gluten: 'Gluten',
    lactose: 'Lactose',
    yeast: 'Yeast',
    treeNuts: 'Tree nuts',
    peanuts: 'Peanuts',
    dairy: 'Dairy',
    eggs: 'Eggs',
    sulfites: 'Sulfites',
    soy: 'Soy',
    wheat: 'Wheat',
    shellfish: 'Shellfish',
    fish: 'Fish',
    mushrooms: 'Mushrooms',
    sesame: 'Sesame',
    monosodiumGlutamateMsg: 'Monosodium glutamate (MSG)',
    caffeine: 'Caffeine',
    fodmaps: 'FODMAPs',
    unknownDefaultOpenApi: '11184809'
} as const;
export type DietRestriction = typeof DietRestriction[keyof typeof DietRestriction];


export function instanceOfDietRestriction(value: any): boolean {
    for (const key in DietRestriction) {
        if (Object.prototype.hasOwnProperty.call(DietRestriction, key)) {
            if (DietRestriction[key as keyof typeof DietRestriction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DietRestrictionFromJSON(json: any): DietRestriction {
    return DietRestrictionFromJSONTyped(json, false);
}

export function DietRestrictionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DietRestriction {
    return json as DietRestriction;
}

export function DietRestrictionToJSON(value?: DietRestriction | null): any {
    return value as any;
}

export function DietRestrictionToJSONTyped(value: any, ignoreDiscriminator: boolean): DietRestriction {
    return value as DietRestriction;
}
