/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface FoodLogInputServing
 */
export interface FoodLogInputServing {
    /**
     * Stable serving identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof FoodLogInputServing
     */
    id: number;
    /**
     * How many of that serving were consumed.
     * @type {number}
     * @memberof FoodLogInputServing
     */
    quantity: number;
}

/**
 * Check if a given object implements the FoodLogInputServing interface.
 */
export function instanceOfFoodLogInputServing(value: object): value is FoodLogInputServing {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function FoodLogInputServingFromJSON(json: any): FoodLogInputServing {
    return FoodLogInputServingFromJSONTyped(json, false);
}

export function FoodLogInputServingFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodLogInputServing {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'quantity': json['quantity'],
    };
}

export function FoodLogInputServingToJSON(json: any): FoodLogInputServing {
    return FoodLogInputServingToJSONTyped(json, false);
}

export function FoodLogInputServingToJSONTyped(value?: FoodLogInputServing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'quantity': value['quantity'],
    };
}
