/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DetectedFood } from './DetectedFood.js';
import {
    DetectedFoodFromJSON,
    DetectedFoodFromJSONTyped,
    DetectedFoodToJSON,
    DetectedFoodToJSONTyped,
} from './DetectedFood.js';

/**
 *
 * @export
 * @interface FoodDetection
 */
export interface FoodDetection {
    /**
     * Photo scans only; absent on text scans.
     * @type {string}
     * @memberof FoodDetection
     */
    confidenceScore?: string;
    /**
     *
     * @type {DetectedFood}
     * @memberof FoodDetection
     */
    food: DetectedFood;
}

/**
 * Check if a given object implements the FoodDetection interface.
 */
export function instanceOfFoodDetection(value: object): value is FoodDetection {
    if (!('food' in value) || value['food'] === undefined) return false;
    return true;
}

export function FoodDetectionFromJSON(json: any): FoodDetection {
    return FoodDetectionFromJSONTyped(json, false);
}

export function FoodDetectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodDetection {
    if (json == null) {
        return json;
    }
    return {

        'confidenceScore': json['confidence_score'] == null ? undefined : json['confidence_score'],
        'food': DetectedFoodFromJSON(json['food']),
    };
}

export function FoodDetectionToJSON(json: any): FoodDetection {
    return FoodDetectionToJSONTyped(json, false);
}

export function FoodDetectionToJSONTyped(value?: FoodDetection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'confidence_score': value['confidenceScore'],
        'food': DetectedFoodToJSON(value['food']),
    };
}
