/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **What you can build** - **Scan food** — detect foods and nutrition from a meal photo or a plain-English description, and correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LoggedFood } from './LoggedFood.js';
import {
    LoggedFoodFromJSON,
    LoggedFoodFromJSONTyped,
    LoggedFoodToJSON,
    LoggedFoodToJSONTyped,
} from './LoggedFood.js';

/**
 *
 * @export
 * @interface FoodLog
 */
export interface FoodLog {
    /**
     * Stable food-log identifier; the upstream 400 response explicitly rejects non-UUID values.
     * @type {string}
     * @memberof FoodLog
     */
    id: string;
    /**
     *
     * @type {Array<LoggedFood>}
     * @memberof FoodLog
     */
    foods: Array<LoggedFood>;
    /**
     * Returned UTC timestamp. Treat as an opaque string because deployed responses are not consistently RFC 3339 formatted.
     * @type {string}
     * @memberof FoodLog
     */
    timestampUtc: string;
    /**
     *
     * @type {string}
     * @memberof FoodLog
     */
    name?: string | null;
}

/**
 * Check if a given object implements the FoodLog interface.
 */
export function instanceOfFoodLog(value: object): value is FoodLog {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('foods' in value) || value['foods'] === undefined) return false;
    if ((!('timestampUtc' in (value as Record<string, any>)) && !('timestamp_utc' in (value as Record<string, any>))) || ((value as Record<string, any>)['timestampUtc'] === undefined && (value as Record<string, any>)['timestamp_utc'] === undefined)) return false;
    return true;
}

export function FoodLogFromJSON(json: any): FoodLog {
    return FoodLogFromJSONTyped(json, false);
}

export function FoodLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodLog {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'foods': ((json['foods'] as Array<any>).map(LoggedFoodFromJSON)),
        'timestampUtc': json['timestamp_utc'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
    };
}

export function FoodLogToJSON(json: any): FoodLog {
    return FoodLogToJSONTyped(json, false);
}

export function FoodLogToJSONTyped(value?: FoodLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'foods': ((value['foods'] as Array<any>).map(LoggedFoodToJSON)),
        'timestamp_utc': value['timestampUtc'],
        'name': value['name'],
    };
}
