/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NutritionFacts } from './NutritionFacts.js';
import {
    NutritionFactsFromJSON,
    NutritionFactsFromJSONTyped,
    NutritionFactsToJSON,
    NutritionFactsToJSONTyped,
} from './NutritionFacts.js';
import type { ServingOption } from './ServingOption.js';
import {
    ServingOptionFromJSON,
    ServingOptionFromJSONTyped,
    ServingOptionToJSON,
    ServingOptionToJSONTyped,
} from './ServingOption.js';

/**
 *
 * @export
 * @interface FoodSearchItem
 */
export interface FoodSearchItem {
    /**
     * Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof FoodSearchItem
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof FoodSearchItem
     */
    name: string;
    /**
     * Absent for generic (non-branded) foods.
     * @type {string}
     * @memberof FoodSearchItem
     */
    brandName?: string;
    /**
     *
     * @type {NutritionFacts}
     * @memberof FoodSearchItem
     */
    nutrients: NutritionFacts;
    /**
     * Glycemic index.
     * @type {number}
     * @memberof FoodSearchItem
     */
    glycemicIndex?: number;
    /**
     * Glycemic load.
     * @type {number}
     * @memberof FoodSearchItem
     */
    glycemicLoad?: number;
    /**
     * URL of a picture of the food, when the database has one.
     * @type {string}
     * @memberof FoodSearchItem
     */
    imageUrl?: string;
    /**
     * The product's barcode, for branded foods that have one.
     * @type {string}
     * @memberof FoodSearchItem
     */
    upc?: string;
    /**
     *
     * @type {Array<ServingOption>}
     * @memberof FoodSearchItem
     */
    servings: Array<ServingOption>;
}

/**
 * Check if a given object implements the FoodSearchItem interface.
 */
export function instanceOfFoodSearchItem(value: object): value is FoodSearchItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nutrients' in value) || value['nutrients'] === undefined) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    return true;
}

export function FoodSearchItemFromJSON(json: any): FoodSearchItem {
    return FoodSearchItemFromJSONTyped(json, false);
}

export function FoodSearchItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodSearchItem {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'nutrients': NutritionFactsFromJSON(json['nutrients']),
        'glycemicIndex': json['glycemic_index'] == null ? undefined : json['glycemic_index'],
        'glycemicLoad': json['glycemic_load'] == null ? undefined : json['glycemic_load'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'upc': json['upc'] == null ? undefined : json['upc'],
        'servings': ((json['servings'] as Array<any>).map(ServingOptionFromJSON)),
    };
}

export function FoodSearchItemToJSON(json: any): FoodSearchItem {
    return FoodSearchItemToJSONTyped(json, false);
}

export function FoodSearchItemToJSONTyped(value?: FoodSearchItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
        'brand_name': value['brandName'],
        'nutrients': NutritionFactsToJSON(value['nutrients']),
        'glycemic_index': value['glycemicIndex'],
        'glycemic_load': value['glycemicLoad'],
        'image_url': value['imageUrl'],
        'upc': value['upc'],
        'servings': ((value['servings'] as Array<any>).map(ServingOptionToJSON)),
    };
}
