/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface FoodLogInputServing
 */
export interface FoodLogInputServing {
    /**
     * Stable serving identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof FoodLogInputServing
     */
    id: number;
    /**
     * How many of that serving were consumed.
     * @type {number}
     * @memberof FoodLogInputServing
     */
    quantity: number;
}

/**
 * Check if a given object implements the FoodLogInputServing interface.
 */
export function instanceOfFoodLogInputServing(value: object): value is FoodLogInputServing {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function FoodLogInputServingFromJSON(json: any): FoodLogInputServing {
    return FoodLogInputServingFromJSONTyped(json, false);
}

export function FoodLogInputServingFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodLogInputServing {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'quantity': json['quantity'],
    };
}

export function FoodLogInputServingToJSON(json: any): FoodLogInputServing {
    return FoodLogInputServingToJSONTyped(json, false);
}

export function FoodLogInputServingToJSONTyped(value?: FoodLogInputServing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'quantity': value['quantity'],
    };
}
