/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodSearchItem } from './FoodSearchItem.js';
import {
    FoodSearchItemFromJSON,
    FoodSearchItemFromJSONTyped,
    FoodSearchItemToJSON,
    FoodSearchItemToJSONTyped,
} from './FoodSearchItem.js';

/**
 *
 * @export
 * @interface FoodSearchResults
 */
export interface FoodSearchResults {
    /**
     * Total number of matches in the database; may exceed the number of items returned.
     * @type {number}
     * @memberof FoodSearchResults
     */
    totalCount: number;
    /**
     *
     * @type {Array<FoodSearchItem>}
     * @memberof FoodSearchResults
     */
    items: Array<FoodSearchItem>;
}

/**
 * Check if a given object implements the FoodSearchResults interface.
 */
export function instanceOfFoodSearchResults(value: object): value is FoodSearchResults {
    if ((!('totalCount' in (value as Record<string, any>)) && !('total_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalCount'] === undefined && (value as Record<string, any>)['total_count'] === undefined)) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function FoodSearchResultsFromJSON(json: any): FoodSearchResults {
    return FoodSearchResultsFromJSONTyped(json, false);
}

export function FoodSearchResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodSearchResults {
    if (json == null) {
        return json;
    }
    return {

        'totalCount': json['total_count'],
        'items': ((json['items'] as Array<any>).map(FoodSearchItemFromJSON)),
    };
}

export function FoodSearchResultsToJSON(json: any): FoodSearchResults {
    return FoodSearchResultsToJSONTyped(json, false);
}

export function FoodSearchResultsToJSONTyped(value?: FoodSearchResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'total_count': value['totalCount'],
        'items': ((value['items'] as Array<any>).map(FoodSearchItemToJSON)),
    };
}
