/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LoggedFood } from './LoggedFood.js';
import {
    LoggedFoodFromJSON,
    LoggedFoodFromJSONTyped,
    LoggedFoodToJSON,
    LoggedFoodToJSONTyped,
} from './LoggedFood.js';

/**
 *
 * @export
 * @interface FoodLog
 */
export interface FoodLog {
    /**
     * Stable food-log identifier; the upstream 400 response explicitly rejects non-UUID values.
     * @type {string}
     * @memberof FoodLog
     */
    id: string;
    /**
     *
     * @type {Array<LoggedFood>}
     * @memberof FoodLog
     */
    foods: Array<LoggedFood>;
    /**
     *
     * @type {string}
     * @memberof FoodLog
     */
    timestampUtc: string;
    /**
     *
     * @type {string}
     * @memberof FoodLog
     */
    name?: string | null;
}

/**
 * Check if a given object implements the FoodLog interface.
 */
export function instanceOfFoodLog(value: object): value is FoodLog {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('foods' in value) || value['foods'] === undefined) return false;
    if ((!('timestampUtc' in (value as Record<string, any>)) && !('timestamp_utc' in (value as Record<string, any>))) || ((value as Record<string, any>)['timestampUtc'] === undefined && (value as Record<string, any>)['timestamp_utc'] === undefined)) return false;
    return true;
}

export function FoodLogFromJSON(json: any): FoodLog {
    return FoodLogFromJSONTyped(json, false);
}

export function FoodLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodLog {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'foods': ((json['foods'] as Array<any>).map(LoggedFoodFromJSON)),
        'timestampUtc': json['timestamp_utc'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
    };
}

export function FoodLogToJSON(json: any): FoodLog {
    return FoodLogToJSONTyped(json, false);
}

export function FoodLogToJSONTyped(value?: FoodLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'foods': ((value['foods'] as Array<any>).map(LoggedFoodToJSON)),
        'timestamp_utc': value['timestampUtc'],
        'name': value['name'],
    };
}
