/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ServingOption } from './ServingOption.js';
import {
    ServingOptionFromJSON,
    ServingOptionFromJSONTyped,
    ServingOptionToJSON,
    ServingOptionToJSONTyped,
} from './ServingOption.js';

/**
 *
 * @export
 * @interface FoodSearchItem
 */
export interface FoodSearchItem {
    /**
     * Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof FoodSearchItem
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof FoodSearchItem
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof FoodSearchItem
     */
    brandName: string | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    energy: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    protein: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    carbs: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    netCarbs: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    fat: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    fatTotalSaturated: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    fiber: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    sugars: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    addedSugars: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    sodium: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    potassium: number | null;
    /**
     *
     * @type {number}
     * @memberof FoodSearchItem
     */
    cholesterol: number | null;
    /**
     * Glycemic index.
     * @type {number}
     * @memberof FoodSearchItem
     */
    gi: number | null;
    /**
     * Glycemic load.
     * @type {number}
     * @memberof FoodSearchItem
     */
    gl: number | null;
    /**
     *
     * @type {string}
     * @memberof FoodSearchItem
     */
    photoUrl: string | null;
    /**
     *
     * @type {Array<ServingOption>}
     * @memberof FoodSearchItem
     */
    servings: Array<ServingOption>;
}

/**
 * Check if a given object implements the FoodSearchItem interface.
 */
export function instanceOfFoodSearchItem(value: object): value is FoodSearchItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('brandName' in (value as Record<string, any>)) && !('brand_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['brandName'] === undefined && (value as Record<string, any>)['brand_name'] === undefined)) return false;
    if (!('energy' in value) || value['energy'] === undefined) return false;
    if (!('protein' in value) || value['protein'] === undefined) return false;
    if (!('carbs' in value) || value['carbs'] === undefined) return false;
    if ((!('netCarbs' in (value as Record<string, any>)) && !('net_carbs' in (value as Record<string, any>))) || ((value as Record<string, any>)['netCarbs'] === undefined && (value as Record<string, any>)['net_carbs'] === undefined)) return false;
    if (!('fat' in value) || value['fat'] === undefined) return false;
    if ((!('fatTotalSaturated' in (value as Record<string, any>)) && !('fat_total_saturated' in (value as Record<string, any>))) || ((value as Record<string, any>)['fatTotalSaturated'] === undefined && (value as Record<string, any>)['fat_total_saturated'] === undefined)) return false;
    if (!('fiber' in value) || value['fiber'] === undefined) return false;
    if (!('sugars' in value) || value['sugars'] === undefined) return false;
    if ((!('addedSugars' in (value as Record<string, any>)) && !('added_sugars' in (value as Record<string, any>))) || ((value as Record<string, any>)['addedSugars'] === undefined && (value as Record<string, any>)['added_sugars'] === undefined)) return false;
    if (!('sodium' in value) || value['sodium'] === undefined) return false;
    if (!('potassium' in value) || value['potassium'] === undefined) return false;
    if (!('cholesterol' in value) || value['cholesterol'] === undefined) return false;
    if (!('gi' in value) || value['gi'] === undefined) return false;
    if (!('gl' in value) || value['gl'] === undefined) return false;
    if ((!('photoUrl' in (value as Record<string, any>)) && !('photo_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['photoUrl'] === undefined && (value as Record<string, any>)['photo_url'] === undefined)) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    return true;
}

export function FoodSearchItemFromJSON(json: any): FoodSearchItem {
    return FoodSearchItemFromJSONTyped(json, false);
}

export function FoodSearchItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodSearchItem {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
        'brandName': json['brand_name'],
        'energy': json['energy'],
        'protein': json['protein'],
        'carbs': json['carbs'],
        'netCarbs': json['net_carbs'],
        'fat': json['fat'],
        'fatTotalSaturated': json['fat_total_saturated'],
        'fiber': json['fiber'],
        'sugars': json['sugars'],
        'addedSugars': json['added_sugars'],
        'sodium': json['sodium'],
        'potassium': json['potassium'],
        'cholesterol': json['cholesterol'],
        'gi': json['gi'],
        'gl': json['gl'],
        'photoUrl': json['photo_url'],
        'servings': ((json['servings'] as Array<any>).map(ServingOptionFromJSON)),
    };
}

export function FoodSearchItemToJSON(json: any): FoodSearchItem {
    return FoodSearchItemToJSONTyped(json, false);
}

export function FoodSearchItemToJSONTyped(value?: FoodSearchItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
        'brand_name': value['brandName'],
        'energy': value['energy'],
        'protein': value['protein'],
        'carbs': value['carbs'],
        'net_carbs': value['netCarbs'],
        'fat': value['fat'],
        'fat_total_saturated': value['fatTotalSaturated'],
        'fiber': value['fiber'],
        'sugars': value['sugars'],
        'added_sugars': value['addedSugars'],
        'sodium': value['sodium'],
        'potassium': value['potassium'],
        'cholesterol': value['cholesterol'],
        'gi': value['gi'],
        'gl': value['gl'],
        'photo_url': value['photoUrl'],
        'servings': ((value['servings'] as Array<any>).map(ServingOptionToJSON)),
    };
}
