/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const FoodCategory = {
    general: 'general',
    branded: 'branded',
    recipe: 'recipe',
    unknownDefaultOpenApi: '11184809'
} as const;
export type FoodCategory = typeof FoodCategory[keyof typeof FoodCategory];


export function instanceOfFoodCategory(value: any): boolean {
    for (const key in FoodCategory) {
        if (Object.prototype.hasOwnProperty.call(FoodCategory, key)) {
            if (FoodCategory[key as keyof typeof FoodCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FoodCategoryFromJSON(json: any): FoodCategory {
    return FoodCategoryFromJSONTyped(json, false);
}

export function FoodCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodCategory {
    return json as FoodCategory;
}

export function FoodCategoryToJSON(value?: FoodCategory | null): any {
    return value as any;
}

export function FoodCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): FoodCategory {
    return value as FoodCategory;
}
