/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **What you can build** - **Scan food** — detect foods and nutrition from a meal photo or a plain-English description, and correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Sex } from './Sex.js';
import {
    SexFromJSON,
    SexFromJSONTyped,
    SexToJSON,
    SexToJSONTyped,
} from './Sex.js';
import type { MedicalCondition } from './MedicalCondition.js';
import {
    MedicalConditionFromJSON,
    MedicalConditionFromJSONTyped,
    MedicalConditionToJSON,
    MedicalConditionToJSONTyped,
} from './MedicalCondition.js';
import type { Height } from './Height.js';
import {
    HeightFromJSON,
    HeightFromJSONTyped,
    HeightToJSON,
    HeightToJSONTyped,
} from './Height.js';
import type { Weight } from './Weight.js';
import {
    WeightFromJSON,
    WeightFromJSONTyped,
    WeightToJSON,
    WeightToJSONTyped,
} from './Weight.js';
import type { ActivityLevel } from './ActivityLevel.js';
import {
    ActivityLevelFromJSON,
    ActivityLevelFromJSONTyped,
    ActivityLevelToJSON,
    ActivityLevelToJSONTyped,
} from './ActivityLevel.js';

/**
 *
 * @export
 * @interface GlucosePredictionProfile
 */
export interface GlucosePredictionProfile {
    /**
     *
     * @type {number}
     * @memberof GlucosePredictionProfile
     */
    age: number;
    /**
     *
     * @type {Sex}
     * @memberof GlucosePredictionProfile
     */
    sex: Sex;
    /**
     *
     * @type {Height}
     * @memberof GlucosePredictionProfile
     */
    height: Height;
    /**
     *
     * @type {Weight}
     * @memberof GlucosePredictionProfile
     */
    weight: Weight;
    /**
     *
     * @type {ActivityLevel}
     * @memberof GlucosePredictionProfile
     */
    activityLevel?: ActivityLevel;
    /**
     * Omit it (or send []) if none apply. Type 1 diabetes is not supported by the prediction model.
     * @type {Array<MedicalCondition>}
     * @memberof GlucosePredictionProfile
     */
    healthConditions?: Array<MedicalCondition>;
}



/**
 * Check if a given object implements the GlucosePredictionProfile interface.
 */
export function instanceOfGlucosePredictionProfile(value: object): value is GlucosePredictionProfile {
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('sex' in value) || value['sex'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function GlucosePredictionProfileFromJSON(json: any): GlucosePredictionProfile {
    return GlucosePredictionProfileFromJSONTyped(json, false);
}

export function GlucosePredictionProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlucosePredictionProfile {
    if (json == null) {
        return json;
    }
    return {

        'age': json['age'],
        'sex': SexFromJSON(json['sex']),
        'height': HeightFromJSON(json['height']),
        'weight': WeightFromJSON(json['weight']),
        'activityLevel': json['activity_level'] == null ? undefined : ActivityLevelFromJSON(json['activity_level']),
        'healthConditions': json['health_conditions'] == null ? undefined : ((json['health_conditions'] as Array<any>).map(MedicalConditionFromJSON)),
    };
}

export function GlucosePredictionProfileToJSON(json: any): GlucosePredictionProfile {
    return GlucosePredictionProfileToJSONTyped(json, false);
}

export function GlucosePredictionProfileToJSONTyped(value?: GlucosePredictionProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'age': value['age'],
        'sex': SexToJSON(value['sex']),
        'height': HeightToJSON(value['height']),
        'weight': WeightToJSON(value['weight']),
        'activity_level': ActivityLevelToJSON(value['activityLevel']),
        'health_conditions': value['healthConditions'] == null ? undefined : ((value['healthConditions'] as Array<any>).map(MedicalConditionToJSON)),
    };
}
