/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MedicalCondition } from './MedicalCondition.js';
import {
    MedicalConditionFromJSON,
    MedicalConditionFromJSONTyped,
    MedicalConditionToJSON,
    MedicalConditionToJSONTyped,
} from './MedicalCondition.js';
import type { Gender } from './Gender.js';
import {
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
    GenderToJSONTyped,
} from './Gender.js';
import type { ActivityLevel } from './ActivityLevel.js';
import {
    ActivityLevelFromJSON,
    ActivityLevelFromJSONTyped,
    ActivityLevelToJSON,
    ActivityLevelToJSONTyped,
} from './ActivityLevel.js';

/**
 *
 * @export
 * @interface GlucosePredictionProfile
 */
export interface GlucosePredictionProfile {
    /**
     *
     * @type {number}
     * @memberof GlucosePredictionProfile
     */
    age: number;
    /**
     *
     * @type {Gender}
     * @memberof GlucosePredictionProfile
     */
    gender: Gender;
    /**
     * Inches.
     * @type {number}
     * @memberof GlucosePredictionProfile
     */
    height: number;
    /**
     * Pounds.
     * @type {number}
     * @memberof GlucosePredictionProfile
     */
    weight: number;
    /**
     *
     * @type {ActivityLevel}
     * @memberof GlucosePredictionProfile
     */
    activityLevel?: ActivityLevel;
    /**
     * Case-sensitive. Type 1 diabetes is not supported by the prediction model.
     * @type {Array<MedicalCondition>}
     * @memberof GlucosePredictionProfile
     */
    healthConditions?: Array<MedicalCondition>;
}



/**
 * Check if a given object implements the GlucosePredictionProfile interface.
 */
export function instanceOfGlucosePredictionProfile(value: object): value is GlucosePredictionProfile {
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function GlucosePredictionProfileFromJSON(json: any): GlucosePredictionProfile {
    return GlucosePredictionProfileFromJSONTyped(json, false);
}

export function GlucosePredictionProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlucosePredictionProfile {
    if (json == null) {
        return json;
    }
    return {

        'age': json['age'],
        'gender': GenderFromJSON(json['gender']),
        'height': json['height'],
        'weight': json['weight'],
        'activityLevel': json['activity_level'] == null ? undefined : ActivityLevelFromJSON(json['activity_level']),
        'healthConditions': json['health_conditions'] == null ? undefined : ((json['health_conditions'] as Array<any>).map(MedicalConditionFromJSON)),
    };
}

export function GlucosePredictionProfileToJSON(json: any): GlucosePredictionProfile {
    return GlucosePredictionProfileToJSONTyped(json, false);
}

export function GlucosePredictionProfileToJSONTyped(value?: GlucosePredictionProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'age': value['age'],
        'gender': GenderToJSON(value['gender']),
        'height': value['height'],
        'weight': value['weight'],
        'activity_level': ActivityLevelToJSON(value['activityLevel']),
        'health_conditions': value['healthConditions'] == null ? undefined : ((value['healthConditions'] as Array<any>).map(MedicalConditionToJSON)),
    };
}
