/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface GlucosePrediction
 */
export interface GlucosePrediction {
    /**
     * The predicted glucose curve as [minutes after start_time, mg/dL] points at 15-minute intervals.
     * @type {Array<Array<number>>}
     * @memberof GlucosePrediction
     */
    cgp: Array<Array<number>>;
    /**
     *
     * @type {string}
     * @memberof GlucosePrediction
     */
    scoring: string;
    /**
     * The chart's suggested Y-axis lower bound (mg/dL) — a fixed target-range bound, NOT the minimum of the predicted curve.
     * @type {number}
     * @memberof GlucosePrediction
     */
    cgpMin: number;
    /**
     * The chart's suggested Y-axis upper bound (mg/dL): 180 with Type 2 diabetes in health_conditions, otherwise 140. NOT the maximum of the predicted curve.
     * @type {number}
     * @memberof GlucosePrediction
     */
    cgpMax: number;
}

/**
 * Check if a given object implements the GlucosePrediction interface.
 */
export function instanceOfGlucosePrediction(value: object): value is GlucosePrediction {
    if (!('cgp' in value) || value['cgp'] === undefined) return false;
    if (!('scoring' in value) || value['scoring'] === undefined) return false;
    if ((!('cgpMin' in (value as Record<string, any>)) && !('cgp_min' in (value as Record<string, any>))) || ((value as Record<string, any>)['cgpMin'] === undefined && (value as Record<string, any>)['cgp_min'] === undefined)) return false;
    if ((!('cgpMax' in (value as Record<string, any>)) && !('cgp_max' in (value as Record<string, any>))) || ((value as Record<string, any>)['cgpMax'] === undefined && (value as Record<string, any>)['cgp_max'] === undefined)) return false;
    return true;
}

export function GlucosePredictionFromJSON(json: any): GlucosePrediction {
    return GlucosePredictionFromJSONTyped(json, false);
}

export function GlucosePredictionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlucosePrediction {
    if (json == null) {
        return json;
    }
    return {

        'cgp': json['cgp'],
        'scoring': json['scoring'],
        'cgpMin': json['cgp_min'],
        'cgpMax': json['cgp_max'],
    };
}

export function GlucosePredictionToJSON(json: any): GlucosePrediction {
    return GlucosePredictionToJSONTyped(json, false);
}

export function GlucosePredictionToJSONTyped(value?: GlucosePrediction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'cgp': value['cgp'],
        'scoring': value['scoring'],
        'cgp_min': value['cgpMin'],
        'cgp_max': value['cgpMax'],
    };
}
