/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GlucoseChart } from './GlucoseChart.js';
import {
    GlucoseChartFromJSON,
    GlucoseChartFromJSONTyped,
    GlucoseChartToJSON,
    GlucoseChartToJSONTyped,
} from './GlucoseChart.js';
import type { GlucosePredictionPoint } from './GlucosePredictionPoint.js';
import {
    GlucosePredictionPointFromJSON,
    GlucosePredictionPointFromJSONTyped,
    GlucosePredictionPointToJSON,
    GlucosePredictionPointToJSONTyped,
} from './GlucosePredictionPoint.js';

/**
 *
 * @export
 * @interface GlucosePrediction
 */
export interface GlucosePrediction {
    /**
     * The predicted glucose curve at 15-minute intervals, starting at start_time.
     * @type {Array<GlucosePredictionPoint>}
     * @memberof GlucosePrediction
     */
    prediction: Array<GlucosePredictionPoint>;
    /**
     * The meal's overall glucose impact.
     * @type {string}
     * @memberof GlucosePrediction
     */
    impactScore: string;
    /**
     *
     * @type {GlucoseChart}
     * @memberof GlucosePrediction
     */
    chart: GlucoseChart;
}

/**
 * Check if a given object implements the GlucosePrediction interface.
 */
export function instanceOfGlucosePrediction(value: object): value is GlucosePrediction {
    if (!('prediction' in value) || value['prediction'] === undefined) return false;
    if ((!('impactScore' in (value as Record<string, any>)) && !('impact_score' in (value as Record<string, any>))) || ((value as Record<string, any>)['impactScore'] === undefined && (value as Record<string, any>)['impact_score'] === undefined)) return false;
    if (!('chart' in value) || value['chart'] === undefined) return false;
    return true;
}

export function GlucosePredictionFromJSON(json: any): GlucosePrediction {
    return GlucosePredictionFromJSONTyped(json, false);
}

export function GlucosePredictionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlucosePrediction {
    if (json == null) {
        return json;
    }
    return {

        'prediction': ((json['prediction'] as Array<any>).map(GlucosePredictionPointFromJSON)),
        'impactScore': json['impact_score'],
        'chart': GlucoseChartFromJSON(json['chart']),
    };
}

export function GlucosePredictionToJSON(json: any): GlucosePrediction {
    return GlucosePredictionToJSONTyped(json, false);
}

export function GlucosePredictionToJSONTyped(value?: GlucosePrediction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'prediction': ((value['prediction'] as Array<any>).map(GlucosePredictionPointToJSON)),
        'impact_score': value['impactScore'],
        'chart': GlucoseChartToJSON(value['chart']),
    };
}
