/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodLog } from './FoodLog.js';
import {
    FoodLogFromJSON,
    FoodLogFromJSONTyped,
    FoodLogToJSON,
    FoodLogToJSONTyped,
} from './FoodLog.js';

/**
 *
 * @export
 * @interface ListFoodLogsResponse
 */
export interface ListFoodLogsResponse {
    /**
     *
     * @type {number}
     * @memberof ListFoodLogsResponse
     */
    totalCount: number;
    /**
     * Logs in the range, ordered by timestamp. An empty list is a valid result.
     * @type {Array<FoodLog>}
     * @memberof ListFoodLogsResponse
     */
    items: Array<FoodLog>;
}

/**
 * Check if a given object implements the ListFoodLogsResponse interface.
 */
export function instanceOfListFoodLogsResponse(value: object): value is ListFoodLogsResponse {
    if ((!('totalCount' in (value as Record<string, any>)) && !('total_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalCount'] === undefined && (value as Record<string, any>)['total_count'] === undefined)) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListFoodLogsResponseFromJSON(json: any): ListFoodLogsResponse {
    return ListFoodLogsResponseFromJSONTyped(json, false);
}

export function ListFoodLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFoodLogsResponse {
    if (json == null) {
        return json;
    }
    return {

        'totalCount': json['total_count'],
        'items': ((json['items'] as Array<any>).map(FoodLogFromJSON)),
    };
}

export function ListFoodLogsResponseToJSON(json: any): ListFoodLogsResponse {
    return ListFoodLogsResponseToJSONTyped(json, false);
}

export function ListFoodLogsResponseToJSONTyped(value?: ListFoodLogsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'total_count': value['totalCount'],
        'items': ((value['items'] as Array<any>).map(FoodLogToJSON)),
    };
}
