/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodLogInputServing } from './FoodLogInputServing.js';
import {
    FoodLogInputServingFromJSON,
    FoodLogInputServingFromJSONTyped,
    FoodLogInputServingToJSON,
    FoodLogInputServingToJSONTyped,
} from './FoodLogInputServing.js';
import type { NutritionFacts } from './NutritionFacts.js';
import {
    NutritionFactsFromJSON,
    NutritionFactsFromJSONTyped,
    NutritionFactsToJSON,
    NutritionFactsToJSONTyped,
} from './NutritionFacts.js';
import type { ServingDetails } from './ServingDetails.js';
import {
    ServingDetailsFromJSON,
    ServingDetailsFromJSONTyped,
    ServingDetailsToJSON,
    ServingDetailsToJSONTyped,
} from './ServingDetails.js';

/**
 *
 * @export
 * @interface LoggedFood
 */
export interface LoggedFood {
    /**
     * Stable food identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof LoggedFood
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof LoggedFood
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof LoggedFood
     */
    brandName?: string | null;
    /**
     *
     * @type {string}
     * @memberof LoggedFood
     */
    imageUrl?: string | null;
    /**
     *
     * @type {number}
     * @memberof LoggedFood
     */
    glycemicIndex?: number | null;
    /**
     *
     * @type {number}
     * @memberof LoggedFood
     */
    glycemicLoad?: number | null;
    /**
     *
     * @type {NutritionFacts}
     * @memberof LoggedFood
     */
    nutrients: NutritionFacts;
    /**
     *
     * @type {FoodLogInputServing}
     * @memberof LoggedFood
     */
    consumedServing: FoodLogInputServing;
    /**
     *
     * @type {ServingDetails}
     * @memberof LoggedFood
     */
    servingDetails: ServingDetails;
}

/**
 * Check if a given object implements the LoggedFood interface.
 */
export function instanceOfLoggedFood(value: object): value is LoggedFood {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nutrients' in value) || value['nutrients'] === undefined) return false;
    if ((!('consumedServing' in (value as Record<string, any>)) && !('consumed_serving' in (value as Record<string, any>))) || ((value as Record<string, any>)['consumedServing'] === undefined && (value as Record<string, any>)['consumed_serving'] === undefined)) return false;
    if ((!('servingDetails' in (value as Record<string, any>)) && !('serving_details' in (value as Record<string, any>))) || ((value as Record<string, any>)['servingDetails'] === undefined && (value as Record<string, any>)['serving_details'] === undefined)) return false;
    return true;
}

export function LoggedFoodFromJSON(json: any): LoggedFood {
    return LoggedFoodFromJSONTyped(json, false);
}

export function LoggedFoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoggedFood {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
        'brandName': json['brand_name'] === undefined ? undefined : json['brand_name'] === null ? null : json['brand_name'],
        'imageUrl': json['image_url'] === undefined ? undefined : json['image_url'] === null ? null : json['image_url'],
        'glycemicIndex': json['glycemic_index'] === undefined ? undefined : json['glycemic_index'] === null ? null : json['glycemic_index'],
        'glycemicLoad': json['glycemic_load'] === undefined ? undefined : json['glycemic_load'] === null ? null : json['glycemic_load'],
        'nutrients': NutritionFactsFromJSON(json['nutrients']),
        'consumedServing': FoodLogInputServingFromJSON(json['consumed_serving']),
        'servingDetails': ServingDetailsFromJSON(json['serving_details']),
    };
}

export function LoggedFoodToJSON(json: any): LoggedFood {
    return LoggedFoodToJSONTyped(json, false);
}

export function LoggedFoodToJSONTyped(value?: LoggedFood | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
        'brand_name': value['brandName'],
        'image_url': value['imageUrl'],
        'glycemic_index': value['glycemicIndex'],
        'glycemic_load': value['glycemicLoad'],
        'nutrients': NutritionFactsToJSON(value['nutrients']),
        'consumed_serving': FoodLogInputServingToJSON(value['consumedServing']),
        'serving_details': ServingDetailsToJSON(value['servingDetails']),
    };
}
