/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const MedicalCondition = {
    type2Diabetes: 'Type 2 diabetes',
    prediabetes: 'Prediabetes',
    noneOfTheAbove: 'None of the above',
    unknownDefaultOpenApi: '11184809'
} as const;
export type MedicalCondition = typeof MedicalCondition[keyof typeof MedicalCondition];


export function instanceOfMedicalCondition(value: any): boolean {
    for (const key in MedicalCondition) {
        if (Object.prototype.hasOwnProperty.call(MedicalCondition, key)) {
            if (MedicalCondition[key as keyof typeof MedicalCondition] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MedicalConditionFromJSON(json: any): MedicalCondition {
    return MedicalConditionFromJSONTyped(json, false);
}

export function MedicalConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicalCondition {
    return json as MedicalCondition;
}

export function MedicalConditionToJSON(value?: MedicalCondition | null): any {
    return value as any;
}

export function MedicalConditionToJSONTyped(value: any, ignoreDiscriminator: boolean): MedicalCondition {
    return value as MedicalCondition;
}
