/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NaturalLanguageFood } from './NaturalLanguageFood.js';
import {
    NaturalLanguageFoodFromJSON,
    NaturalLanguageFoodFromJSONTyped,
    NaturalLanguageFoodToJSON,
    NaturalLanguageFoodToJSONTyped,
} from './NaturalLanguageFood.js';

/**
 *
 * @export
 * @interface NaturalLanguageFoodDetection
 */
export interface NaturalLanguageFoodDetection {
    /**
     *
     * @type {NaturalLanguageFood}
     * @memberof NaturalLanguageFoodDetection
     */
    food: NaturalLanguageFood;
}

/**
 * Check if a given object implements the NaturalLanguageFoodDetection interface.
 */
export function instanceOfNaturalLanguageFoodDetection(value: object): value is NaturalLanguageFoodDetection {
    if (!('food' in value) || value['food'] === undefined) return false;
    return true;
}

export function NaturalLanguageFoodDetectionFromJSON(json: any): NaturalLanguageFoodDetection {
    return NaturalLanguageFoodDetectionFromJSONTyped(json, false);
}

export function NaturalLanguageFoodDetectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NaturalLanguageFoodDetection {
    if (json == null) {
        return json;
    }
    return {

        'food': NaturalLanguageFoodFromJSON(json['food']),
    };
}

export function NaturalLanguageFoodDetectionToJSON(json: any): NaturalLanguageFoodDetection {
    return NaturalLanguageFoodDetectionToJSONTyped(json, false);
}

export function NaturalLanguageFoodDetectionToJSONTyped(value?: NaturalLanguageFoodDetection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'food': NaturalLanguageFoodToJSON(value['food']),
    };
}
