/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **What you can build** - **Scan food** — detect foods and nutrition from a meal photo or a plain-English description, and correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NutrientAmount } from './NutrientAmount.js';
import {
    NutrientAmountFromJSON,
    NutrientAmountFromJSONTyped,
    NutrientAmountToJSON,
    NutrientAmountToJSONTyped,
} from './NutrientAmount.js';

/**
 *
 * @export
 * @interface NutritionFacts
 */
export interface NutritionFacts {
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    calories?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    protein?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    carbohydrates?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    netCarbohydrates?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    totalFat?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    transFat?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    saturatedFat?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    fiber?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    totalSugars?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    addedSugars?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    cholesterol?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    calcium?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    iron?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    potassium?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    sodium?: NutrientAmount;
    /**
     *
     * @type {NutrientAmount}
     * @memberof NutritionFacts
     */
    vitaminD?: NutrientAmount;
}

/**
 * Check if a given object implements the NutritionFacts interface.
 */
export function instanceOfNutritionFacts(value: object): value is NutritionFacts {
    return true;
}

export function NutritionFactsFromJSON(json: any): NutritionFacts {
    return NutritionFactsFromJSONTyped(json, false);
}

export function NutritionFactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NutritionFacts {
    if (json == null) {
        return json;
    }
    return {

        'calories': json['calories'] == null ? undefined : NutrientAmountFromJSON(json['calories']),
        'protein': json['protein'] == null ? undefined : NutrientAmountFromJSON(json['protein']),
        'carbohydrates': json['carbohydrates'] == null ? undefined : NutrientAmountFromJSON(json['carbohydrates']),
        'netCarbohydrates': json['net_carbohydrates'] == null ? undefined : NutrientAmountFromJSON(json['net_carbohydrates']),
        'totalFat': json['total_fat'] == null ? undefined : NutrientAmountFromJSON(json['total_fat']),
        'transFat': json['trans_fat'] == null ? undefined : NutrientAmountFromJSON(json['trans_fat']),
        'saturatedFat': json['saturated_fat'] == null ? undefined : NutrientAmountFromJSON(json['saturated_fat']),
        'fiber': json['fiber'] == null ? undefined : NutrientAmountFromJSON(json['fiber']),
        'totalSugars': json['total_sugars'] == null ? undefined : NutrientAmountFromJSON(json['total_sugars']),
        'addedSugars': json['added_sugars'] == null ? undefined : NutrientAmountFromJSON(json['added_sugars']),
        'cholesterol': json['cholesterol'] == null ? undefined : NutrientAmountFromJSON(json['cholesterol']),
        'calcium': json['calcium'] == null ? undefined : NutrientAmountFromJSON(json['calcium']),
        'iron': json['iron'] == null ? undefined : NutrientAmountFromJSON(json['iron']),
        'potassium': json['potassium'] == null ? undefined : NutrientAmountFromJSON(json['potassium']),
        'sodium': json['sodium'] == null ? undefined : NutrientAmountFromJSON(json['sodium']),
        'vitaminD': json['vitamin_d'] == null ? undefined : NutrientAmountFromJSON(json['vitamin_d']),
    };
}

export function NutritionFactsToJSON(json: any): NutritionFacts {
    return NutritionFactsToJSONTyped(json, false);
}

export function NutritionFactsToJSONTyped(value?: NutritionFacts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'calories': NutrientAmountToJSON(value['calories']),
        'protein': NutrientAmountToJSON(value['protein']),
        'carbohydrates': NutrientAmountToJSON(value['carbohydrates']),
        'net_carbohydrates': NutrientAmountToJSON(value['netCarbohydrates']),
        'total_fat': NutrientAmountToJSON(value['totalFat']),
        'trans_fat': NutrientAmountToJSON(value['transFat']),
        'saturated_fat': NutrientAmountToJSON(value['saturatedFat']),
        'fiber': NutrientAmountToJSON(value['fiber']),
        'total_sugars': NutrientAmountToJSON(value['totalSugars']),
        'added_sugars': NutrientAmountToJSON(value['addedSugars']),
        'cholesterol': NutrientAmountToJSON(value['cholesterol']),
        'calcium': NutrientAmountToJSON(value['calcium']),
        'iron': NutrientAmountToJSON(value['iron']),
        'potassium': NutrientAmountToJSON(value['potassium']),
        'sodium': NutrientAmountToJSON(value['sodium']),
        'vitamin_d': NutrientAmountToJSON(value['vitaminD']),
    };
}
