/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface NutrientAmount
 */
export interface NutrientAmount {
    /**
     *
     * @type {number}
     * @memberof NutrientAmount
     */
    value: number;
    /**
     *
     * @type {string}
     * @memberof NutrientAmount
     */
    unit: string;
}

/**
 * Check if a given object implements the NutrientAmount interface.
 */
export function instanceOfNutrientAmount(value: object): value is NutrientAmount {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function NutrientAmountFromJSON(json: any): NutrientAmount {
    return NutrientAmountFromJSONTyped(json, false);
}

export function NutrientAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): NutrientAmount {
    if (json == null) {
        return json;
    }
    return {

        'value': json['value'],
        'unit': json['unit'],
    };
}

export function NutrientAmountToJSON(json: any): NutrientAmount {
    return NutrientAmountToJSONTyped(json, false);
}

export function NutrientAmountToJSONTyped(value?: NutrientAmount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'value': value['value'],
        'unit': value['unit'],
    };
}
