/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GlucosePredictionPoint } from './GlucosePredictionPoint.js';
import {
    GlucosePredictionPointFromJSON,
    GlucosePredictionPointFromJSONTyped,
    GlucosePredictionPointToJSON,
    GlucosePredictionPointToJSONTyped,
} from './GlucosePredictionPoint.js';

/**
 *
 * @export
 * @interface PhotoScanGlucoseImpact
 */
export interface PhotoScanGlucoseImpact {
    /**
     *
     * @type {string}
     * @memberof PhotoScanGlucoseImpact
     */
    impactScore: string;
    /**
     *
     * @type {Array<GlucosePredictionPoint>}
     * @memberof PhotoScanGlucoseImpact
     */
    prediction: Array<GlucosePredictionPoint>;
}

/**
 * Check if a given object implements the PhotoScanGlucoseImpact interface.
 */
export function instanceOfPhotoScanGlucoseImpact(value: object): value is PhotoScanGlucoseImpact {
    if ((!('impactScore' in (value as Record<string, any>)) && !('impact_score' in (value as Record<string, any>))) || ((value as Record<string, any>)['impactScore'] === undefined && (value as Record<string, any>)['impact_score'] === undefined)) return false;
    if (!('prediction' in value) || value['prediction'] === undefined) return false;
    return true;
}

export function PhotoScanGlucoseImpactFromJSON(json: any): PhotoScanGlucoseImpact {
    return PhotoScanGlucoseImpactFromJSONTyped(json, false);
}

export function PhotoScanGlucoseImpactFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotoScanGlucoseImpact {
    if (json == null) {
        return json;
    }
    return {

        'impactScore': json['impact_score'],
        'prediction': ((json['prediction'] as Array<any>).map(GlucosePredictionPointFromJSON)),
    };
}

export function PhotoScanGlucoseImpactToJSON(json: any): PhotoScanGlucoseImpact {
    return PhotoScanGlucoseImpactToJSONTyped(json, false);
}

export function PhotoScanGlucoseImpactToJSONTyped(value?: PhotoScanGlucoseImpact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'impact_score': value['impactScore'],
        'prediction': ((value['prediction'] as Array<any>).map(GlucosePredictionPointToJSON)),
    };
}
