/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface Restaurant
 */
export interface Restaurant {
    /**
     * When coordinates are provided and the name matches no restaurant, results may be menu items instead.
     * @type {RestaurantTypeEnum}
     * @memberof Restaurant
     */
    type: RestaurantTypeEnum;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    name: string;
    /**
     *
     * @type {boolean}
     * @memberof Restaurant
     */
    isChain?: boolean;
    /**
     * Distance from (latitude, longitude) in meters; present only when coordinates were provided.
     * @type {number}
     * @memberof Restaurant
     */
    distance?: number;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    city?: string;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    address1?: string;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    address2?: string;
}


/**
 * @export
 */
export const RestaurantTypeEnum = {
    restaurant: 'restaurant',
    menuItem: 'menu_item',
    unknownDefaultOpenApi: '11184809'
} as const;
export type RestaurantTypeEnum = typeof RestaurantTypeEnum[keyof typeof RestaurantTypeEnum];


/**
 * Check if a given object implements the Restaurant interface.
 */
export function instanceOfRestaurant(value: object): value is Restaurant {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RestaurantFromJSON(json: any): Restaurant {
    return RestaurantFromJSONTyped(json, false);
}

export function RestaurantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Restaurant {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'],
        'id': json['id'],
        'name': json['name'],
        'isChain': json['is_chain'] == null ? undefined : json['is_chain'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'city': json['city'] == null ? undefined : json['city'],
        'address1': json['address1'] == null ? undefined : json['address1'],
        'address2': json['address2'] == null ? undefined : json['address2'],
    };
}

export function RestaurantToJSON(json: any): Restaurant {
    return RestaurantToJSONTyped(json, false);
}

export function RestaurantToJSONTyped(value?: Restaurant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'type': value['type'],
        'id': value['id'],
        'name': value['name'],
        'is_chain': value['isChain'],
        'distance': value['distance'],
        'city': value['city'],
        'address1': value['address1'],
        'address2': value['address2'],
    };
}
