/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ServingOption } from './ServingOption.js';
import {
    ServingOptionFromJSON,
    ServingOptionFromJSONTyped,
    ServingOptionToJSON,
    ServingOptionToJSONTyped,
} from './ServingOption.js';

/**
 *
 * @export
 * @interface RestaurantMenuItem
 */
export interface RestaurantMenuItem {
    /**
     *
     * @type {string}
     * @memberof RestaurantMenuItem
     */
    type: string;
    /**
     * Opaque restaurant menu-item identifier.
     * @type {string}
     * @memberof RestaurantMenuItem
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof RestaurantMenuItem
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof RestaurantMenuItem
     */
    restaurantName: string;
    /**
     *
     * @type {boolean}
     * @memberof RestaurantMenuItem
     */
    isChain?: boolean;
    /**
     * Calories (kcal).
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    energy?: number | null;
    /**
     *
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    protein?: number | null;
    /**
     *
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    carbs?: number | null;
    /**
     *
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    netCarbs?: number | null;
    /**
     *
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    fat?: number | null;
    /**
     *
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    fiber?: number | null;
    /**
     *
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    sugars?: number | null;
    /**
     *
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    addedSugars?: number | null;
    /**
     * Glycemic index.
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    gi?: number | null;
    /**
     * Glycemic load.
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    gl?: number | null;
    /**
     *
     * @type {string}
     * @memberof RestaurantMenuItem
     */
    photoUrl?: string | null;
    /**
     * Distance from (latitude, longitude) in meters.
     * @type {number}
     * @memberof RestaurantMenuItem
     */
    distance?: number;
    /**
     *
     * @type {Array<ServingOption>}
     * @memberof RestaurantMenuItem
     */
    servings: Array<ServingOption>;
}

/**
 * Check if a given object implements the RestaurantMenuItem interface.
 */
export function instanceOfRestaurantMenuItem(value: object): value is RestaurantMenuItem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('restaurantName' in (value as Record<string, any>)) && !('restaurant_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['restaurantName'] === undefined && (value as Record<string, any>)['restaurant_name'] === undefined)) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    return true;
}

export function RestaurantMenuItemFromJSON(json: any): RestaurantMenuItem {
    return RestaurantMenuItemFromJSONTyped(json, false);
}

export function RestaurantMenuItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestaurantMenuItem {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'],
        'id': json['id'],
        'name': json['name'],
        'restaurantName': json['restaurant_name'],
        'isChain': json['is_chain'] == null ? undefined : json['is_chain'],
        'energy': json['energy'] === undefined ? undefined : json['energy'] === null ? null : json['energy'],
        'protein': json['protein'] === undefined ? undefined : json['protein'] === null ? null : json['protein'],
        'carbs': json['carbs'] === undefined ? undefined : json['carbs'] === null ? null : json['carbs'],
        'netCarbs': json['net_carbs'] === undefined ? undefined : json['net_carbs'] === null ? null : json['net_carbs'],
        'fat': json['fat'] === undefined ? undefined : json['fat'] === null ? null : json['fat'],
        'fiber': json['fiber'] === undefined ? undefined : json['fiber'] === null ? null : json['fiber'],
        'sugars': json['sugars'] === undefined ? undefined : json['sugars'] === null ? null : json['sugars'],
        'addedSugars': json['added_sugars'] === undefined ? undefined : json['added_sugars'] === null ? null : json['added_sugars'],
        'gi': json['gi'] === undefined ? undefined : json['gi'] === null ? null : json['gi'],
        'gl': json['gl'] === undefined ? undefined : json['gl'] === null ? null : json['gl'],
        'photoUrl': json['photo_url'] === undefined ? undefined : json['photo_url'] === null ? null : json['photo_url'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'servings': ((json['servings'] as Array<any>).map(ServingOptionFromJSON)),
    };
}

export function RestaurantMenuItemToJSON(json: any): RestaurantMenuItem {
    return RestaurantMenuItemToJSONTyped(json, false);
}

export function RestaurantMenuItemToJSONTyped(value?: RestaurantMenuItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'type': value['type'],
        'id': value['id'],
        'name': value['name'],
        'restaurant_name': value['restaurantName'],
        'is_chain': value['isChain'],
        'energy': value['energy'],
        'protein': value['protein'],
        'carbs': value['carbs'],
        'net_carbs': value['netCarbs'],
        'fat': value['fat'],
        'fiber': value['fiber'],
        'sugars': value['sugars'],
        'added_sugars': value['addedSugars'],
        'gi': value['gi'],
        'gl': value['gl'],
        'photo_url': value['photoUrl'],
        'distance': value['distance'],
        'servings': ((value['servings'] as Array<any>).map(ServingOptionToJSON)),
    };
}
