/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface Restaurant
 */
export interface Restaurant {
    /**
     * When coordinates are provided and the name matches no restaurant, results may be menu items instead.
     * @type {RestaurantTypeEnum}
     * @memberof Restaurant
     */
    type: RestaurantTypeEnum;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    name: string;
    /**
     *
     * @type {boolean}
     * @memberof Restaurant
     */
    isChain?: boolean;
    /**
     * Distance from (latitude, longitude) in meters; present only when coordinates were provided.
     * @type {number}
     * @memberof Restaurant
     */
    distance?: number;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    city?: string;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    address1?: string;
    /**
     *
     * @type {string}
     * @memberof Restaurant
     */
    address2?: string;
}


/**
 * @export
 */
export const RestaurantTypeEnum = {
    restaurant: 'restaurant',
    menuItem: 'menu_item',
    unknownDefaultOpenApi: '11184809'
} as const;
export type RestaurantTypeEnum = typeof RestaurantTypeEnum[keyof typeof RestaurantTypeEnum];


/**
 * Check if a given object implements the Restaurant interface.
 */
export function instanceOfRestaurant(value: object): value is Restaurant {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RestaurantFromJSON(json: any): Restaurant {
    return RestaurantFromJSONTyped(json, false);
}

export function RestaurantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Restaurant {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'],
        'id': json['id'],
        'name': json['name'],
        'isChain': json['is_chain'] == null ? undefined : json['is_chain'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'city': json['city'] == null ? undefined : json['city'],
        'address1': json['address1'] == null ? undefined : json['address1'],
        'address2': json['address2'] == null ? undefined : json['address2'],
    };
}

export function RestaurantToJSON(json: any): Restaurant {
    return RestaurantToJSONTyped(json, false);
}

export function RestaurantToJSONTyped(value?: Restaurant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'type': value['type'],
        'id': value['id'],
        'name': value['name'],
        'is_chain': value['isChain'],
        'distance': value['distance'],
        'city': value['city'],
        'address1': value['address1'],
        'address2': value['address2'],
    };
}
