/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **What you can build** - **Scan food** — detect foods and nutrition from a meal photo or a plain-English description, and correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface ScanFoodPhotoBody
 */
export interface ScanFoodPhotoBody {
    /**
     * The meal photo, as an http(s) URL or a base64 data URI (data:image/jpeg;base64,…). Any image of the meal works — a camera photo, a screenshot, or a hosted picture. Formats: JPG, PNG, WEBP, and non-animated GIF. A URL must be publicly fetchable server-side: hosts that block hotlinking or require a login cannot be read. Prefer the URL when the image is already hosted — base64 inflates the payload by ~33%, and request bodies over 5 MB are rejected, so keep raw images under ~3.5 MB when encoding.
     * @type {string}
     * @memberof ScanFoodPhotoBody
     */
    image: string;
}

/**
 * Check if a given object implements the ScanFoodPhotoBody interface.
 */
export function instanceOfScanFoodPhotoBody(value: object): value is ScanFoodPhotoBody {
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function ScanFoodPhotoBodyFromJSON(json: any): ScanFoodPhotoBody {
    return ScanFoodPhotoBodyFromJSONTyped(json, false);
}

export function ScanFoodPhotoBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanFoodPhotoBody {
    if (json == null) {
        return json;
    }
    return {

        'image': json['image'],
    };
}

export function ScanFoodPhotoBodyToJSON(json: any): ScanFoodPhotoBody {
    return ScanFoodPhotoBodyToJSONTyped(json, false);
}

export function ScanFoodPhotoBodyToJSONTyped(value?: ScanFoodPhotoBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'image': value['image'],
    };
}
