/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CompleteScanNutritionFacts } from './CompleteScanNutritionFacts.js';
import {
    CompleteScanNutritionFactsFromJSON,
    CompleteScanNutritionFactsFromJSONTyped,
    CompleteScanNutritionFactsToJSON,
    CompleteScanNutritionFactsToJSONTyped,
} from './CompleteScanNutritionFacts.js';
import type { NaturalLanguageFoodDetection } from './NaturalLanguageFoodDetection.js';
import {
    NaturalLanguageFoodDetectionFromJSON,
    NaturalLanguageFoodDetectionFromJSONTyped,
    NaturalLanguageFoodDetectionToJSON,
    NaturalLanguageFoodDetectionToJSONTyped,
} from './NaturalLanguageFoodDetection.js';

/**
 *
 * @export
 * @interface SearchFoodsByNaturalLanguageResponse
 */
export interface SearchFoodsByNaturalLanguageResponse {
    /**
     *
     * @type {CompleteScanNutritionFacts}
     * @memberof SearchFoodsByNaturalLanguageResponse
     */
    totalNutrients?: CompleteScanNutritionFacts;
    /**
     *
     * @type {Array<NaturalLanguageFoodDetection>}
     * @memberof SearchFoodsByNaturalLanguageResponse
     */
    detections: Array<NaturalLanguageFoodDetection>;
}

/**
 * Check if a given object implements the SearchFoodsByNaturalLanguageResponse interface.
 */
export function instanceOfSearchFoodsByNaturalLanguageResponse(value: object): value is SearchFoodsByNaturalLanguageResponse {
    if (!('detections' in value) || value['detections'] === undefined) return false;
    return true;
}

export function SearchFoodsByNaturalLanguageResponseFromJSON(json: any): SearchFoodsByNaturalLanguageResponse {
    return SearchFoodsByNaturalLanguageResponseFromJSONTyped(json, false);
}

export function SearchFoodsByNaturalLanguageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchFoodsByNaturalLanguageResponse {
    if (json == null) {
        return json;
    }
    return {

        'totalNutrients': json['total_nutrients'] == null ? undefined : CompleteScanNutritionFactsFromJSON(json['total_nutrients']),
        'detections': ((json['detections'] as Array<any>).map(NaturalLanguageFoodDetectionFromJSON)),
    };
}

export function SearchFoodsByNaturalLanguageResponseToJSON(json: any): SearchFoodsByNaturalLanguageResponse {
    return SearchFoodsByNaturalLanguageResponseToJSONTyped(json, false);
}

export function SearchFoodsByNaturalLanguageResponseToJSONTyped(value?: SearchFoodsByNaturalLanguageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'total_nutrients': CompleteScanNutritionFactsToJSON(value['totalNutrients']),
        'detections': ((value['detections'] as Array<any>).map(NaturalLanguageFoodDetectionToJSON)),
    };
}
