/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { RestaurantMenuItem } from './RestaurantMenuItem.js';
import {
    RestaurantMenuItemFromJSON,
    RestaurantMenuItemFromJSONTyped,
    RestaurantMenuItemToJSON,
    RestaurantMenuItemToJSONTyped,
} from './RestaurantMenuItem.js';

/**
 *
 * @export
 * @interface SearchRestaurantMenuItemsResponse
 */
export interface SearchRestaurantMenuItemsResponse {
    /**
     * Total number of matches; may exceed the number of items returned.
     * @type {number}
     * @memberof SearchRestaurantMenuItemsResponse
     */
    totalCount: number;
    /**
     *
     * @type {Array<RestaurantMenuItem>}
     * @memberof SearchRestaurantMenuItemsResponse
     */
    items: Array<RestaurantMenuItem>;
}

/**
 * Check if a given object implements the SearchRestaurantMenuItemsResponse interface.
 */
export function instanceOfSearchRestaurantMenuItemsResponse(value: object): value is SearchRestaurantMenuItemsResponse {
    if ((!('totalCount' in (value as Record<string, any>)) && !('total_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalCount'] === undefined && (value as Record<string, any>)['total_count'] === undefined)) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function SearchRestaurantMenuItemsResponseFromJSON(json: any): SearchRestaurantMenuItemsResponse {
    return SearchRestaurantMenuItemsResponseFromJSONTyped(json, false);
}

export function SearchRestaurantMenuItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRestaurantMenuItemsResponse {
    if (json == null) {
        return json;
    }
    return {

        'totalCount': json['total_count'],
        'items': ((json['items'] as Array<any>).map(RestaurantMenuItemFromJSON)),
    };
}

export function SearchRestaurantMenuItemsResponseToJSON(json: any): SearchRestaurantMenuItemsResponse {
    return SearchRestaurantMenuItemsResponseToJSONTyped(json, false);
}

export function SearchRestaurantMenuItemsResponseToJSONTyped(value?: SearchRestaurantMenuItemsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'total_count': value['totalCount'],
        'items': ((value['items'] as Array<any>).map(RestaurantMenuItemToJSON)),
    };
}
