/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface ServingDetails
 */
export interface ServingDetails {
    /**
     * Stable serving identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof ServingDetails
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof ServingDetails
     */
    quantity: number;
    /**
     *
     * @type {string}
     * @memberof ServingDetails
     */
    unit: string;
    /**
     *
     * @type {number}
     * @memberof ServingDetails
     */
    weightGrams?: number | null;
}

/**
 * Check if a given object implements the ServingDetails interface.
 */
export function instanceOfServingDetails(value: object): value is ServingDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function ServingDetailsFromJSON(json: any): ServingDetails {
    return ServingDetailsFromJSONTyped(json, false);
}

export function ServingDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServingDetails {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'quantity': json['quantity'],
        'unit': json['unit'],
        'weightGrams': json['weight_grams'] === undefined ? undefined : json['weight_grams'] === null ? null : json['weight_grams'],
    };
}

export function ServingDetailsToJSON(json: any): ServingDetails {
    return ServingDetailsToJSONTyped(json, false);
}

export function ServingDetailsToJSONTyped(value?: ServingDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'quantity': value['quantity'],
        'unit': value['unit'],
        'weight_grams': value['weightGrams'],
    };
}
