/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **Security & compliance** — **SOC 2 Type II** · **HIPAA-aligned practices** · **BAA** and **Zero Data Retention (ZDR)** available  **What you can build** - **Scan food** — photo and text food recognition: detect foods and nutrition, then correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface ServingOption
 */
export interface ServingOption {
    /**
     * Stable serving identifier, provisionally narrowed to JavaScript's safe integer range.
     * @type {number}
     * @memberof ServingOption
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof ServingOption
     */
    quantity: number;
    /**
     *
     * @type {string}
     * @memberof ServingOption
     */
    unit: string;
    /**
     * Multiplier applied to the food's nutrition values for this serving.
     * @type {number}
     * @memberof ServingOption
     */
    scalingFactor: number;
    /**
     *
     * @type {number}
     * @memberof ServingOption
     */
    weightGrams: number | null;
    /**
     * Whether this is the default serving for the food.
     * @type {boolean}
     * @memberof ServingOption
     */
    isPrimary: boolean;
}

/**
 * Check if a given object implements the ServingOption interface.
 */
export function instanceOfServingOption(value: object): value is ServingOption {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if ((!('scalingFactor' in (value as Record<string, any>)) && !('scaling_factor' in (value as Record<string, any>))) || ((value as Record<string, any>)['scalingFactor'] === undefined && (value as Record<string, any>)['scaling_factor'] === undefined)) return false;
    if ((!('weightGrams' in (value as Record<string, any>)) && !('weight_grams' in (value as Record<string, any>))) || ((value as Record<string, any>)['weightGrams'] === undefined && (value as Record<string, any>)['weight_grams'] === undefined)) return false;
    if ((!('isPrimary' in (value as Record<string, any>)) && !('is_primary' in (value as Record<string, any>))) || ((value as Record<string, any>)['isPrimary'] === undefined && (value as Record<string, any>)['is_primary'] === undefined)) return false;
    return true;
}

export function ServingOptionFromJSON(json: any): ServingOption {
    return ServingOptionFromJSONTyped(json, false);
}

export function ServingOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServingOption {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'quantity': json['quantity'],
        'unit': json['unit'],
        'scalingFactor': json['scaling_factor'],
        'weightGrams': json['weight_grams'],
        'isPrimary': json['is_primary'],
    };
}

export function ServingOptionToJSON(json: any): ServingOption {
    return ServingOptionToJSONTyped(json, false);
}

export function ServingOptionToJSONTyped(value?: ServingOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'quantity': value['quantity'],
        'unit': value['unit'],
        'scaling_factor': value['scalingFactor'],
        'weight_grams': value['weightGrams'],
        'is_primary': value['isPrimary'],
    };
}
