/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodAlternative } from './FoodAlternative.js';
import {
    FoodAlternativeFromJSON,
    FoodAlternativeFromJSONTyped,
    FoodAlternativeToJSON,
    FoodAlternativeToJSONTyped,
} from './FoodAlternative.js';

/**
 *
 * @export
 * @interface SuggestFoodAlternativesResponse
 */
export interface SuggestFoodAlternativesResponse {
    /**
     * Healthier alternatives matching the restrictions and preferences. An empty array is a valid result, not an error.
     * @type {Array<FoodAlternative>}
     * @memberof SuggestFoodAlternativesResponse
     */
    alternatives: Array<FoodAlternative>;
}

/**
 * Check if a given object implements the SuggestFoodAlternativesResponse interface.
 */
export function instanceOfSuggestFoodAlternativesResponse(value: object): value is SuggestFoodAlternativesResponse {
    if (!('alternatives' in value) || value['alternatives'] === undefined) return false;
    return true;
}

export function SuggestFoodAlternativesResponseFromJSON(json: any): SuggestFoodAlternativesResponse {
    return SuggestFoodAlternativesResponseFromJSONTyped(json, false);
}

export function SuggestFoodAlternativesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestFoodAlternativesResponse {
    if (json == null) {
        return json;
    }
    return {

        'alternatives': ((json['alternatives'] as Array<any>).map(FoodAlternativeFromJSON)),
    };
}

export function SuggestFoodAlternativesResponseToJSON(json: any): SuggestFoodAlternativesResponse {
    return SuggestFoodAlternativesResponseToJSONTyped(json, false);
}

export function SuggestFoodAlternativesResponseToJSONTyped(value?: SuggestFoodAlternativesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'alternatives': ((value['alternatives'] as Array<any>).map(FoodAlternativeToJSON)),
    };
}
