/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DietPreference } from './DietPreference.js';
import {
    DietPreferenceFromJSON,
    DietPreferenceFromJSONTyped,
    DietPreferenceToJSON,
    DietPreferenceToJSONTyped,
} from './DietPreference.js';
import type { DietRestriction } from './DietRestriction.js';
import {
    DietRestrictionFromJSON,
    DietRestrictionFromJSONTyped,
    DietRestrictionToJSON,
    DietRestrictionToJSONTyped,
} from './DietRestriction.js';

/**
 *
 * @export
 * @interface SuggestFoodAlternativesBody
 */
export interface SuggestFoodAlternativesBody {
    /**
     * Allergens/ingredients to avoid; send ["None"] if none apply. Case-sensitive.
     * @type {Array<DietRestriction>}
     * @memberof SuggestFoodAlternativesBody
     */
    dietRestrictions: Array<DietRestriction>;
    /**
     * Dietary patterns to match; send ["None"] if none apply. Case-sensitive.
     * @type {Array<DietPreference>}
     * @memberof SuggestFoodAlternativesBody
     */
    dietPreferences: Array<DietPreference>;
}

/**
 * Check if a given object implements the SuggestFoodAlternativesBody interface.
 */
export function instanceOfSuggestFoodAlternativesBody(value: object): value is SuggestFoodAlternativesBody {
    if ((!('dietRestrictions' in (value as Record<string, any>)) && !('diet_restrictions' in (value as Record<string, any>))) || ((value as Record<string, any>)['dietRestrictions'] === undefined && (value as Record<string, any>)['diet_restrictions'] === undefined)) return false;
    if ((!('dietPreferences' in (value as Record<string, any>)) && !('diet_preferences' in (value as Record<string, any>))) || ((value as Record<string, any>)['dietPreferences'] === undefined && (value as Record<string, any>)['diet_preferences'] === undefined)) return false;
    return true;
}

export function SuggestFoodAlternativesBodyFromJSON(json: any): SuggestFoodAlternativesBody {
    return SuggestFoodAlternativesBodyFromJSONTyped(json, false);
}

export function SuggestFoodAlternativesBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestFoodAlternativesBody {
    if (json == null) {
        return json;
    }
    return {

        'dietRestrictions': ((json['diet_restrictions'] as Array<any>).map(DietRestrictionFromJSON)),
        'dietPreferences': ((json['diet_preferences'] as Array<any>).map(DietPreferenceFromJSON)),
    };
}

export function SuggestFoodAlternativesBodyToJSON(json: any): SuggestFoodAlternativesBody {
    return SuggestFoodAlternativesBodyToJSONTyped(json, false);
}

export function SuggestFoodAlternativesBodyToJSONTyped(value?: SuggestFoodAlternativesBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'diet_restrictions': ((value['dietRestrictions'] as Array<any>).map(DietRestrictionToJSON)),
        'diet_preferences': ((value['dietPreferences'] as Array<any>).map(DietPreferenceToJSON)),
    };
}
