/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **What you can build** - **Scan food** — detect foods and nutrition from a meal photo or a plain-English description, and correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodAlternative } from './FoodAlternative.js';
import {
    FoodAlternativeFromJSON,
    FoodAlternativeFromJSONTyped,
    FoodAlternativeToJSON,
    FoodAlternativeToJSONTyped,
} from './FoodAlternative.js';

/**
 *
 * @export
 * @interface SuggestFoodAlternativesResponse
 */
export interface SuggestFoodAlternativesResponse {
    /**
     * Healthier alternatives matching the restrictions and preferences. An empty array is a valid result, not an error.
     * @type {Array<FoodAlternative>}
     * @memberof SuggestFoodAlternativesResponse
     */
    alternatives: Array<FoodAlternative>;
}

/**
 * Check if a given object implements the SuggestFoodAlternativesResponse interface.
 */
export function instanceOfSuggestFoodAlternativesResponse(value: object): value is SuggestFoodAlternativesResponse {
    if (!('alternatives' in value) || value['alternatives'] === undefined) return false;
    return true;
}

export function SuggestFoodAlternativesResponseFromJSON(json: any): SuggestFoodAlternativesResponse {
    return SuggestFoodAlternativesResponseFromJSONTyped(json, false);
}

export function SuggestFoodAlternativesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestFoodAlternativesResponse {
    if (json == null) {
        return json;
    }
    return {

        'alternatives': ((json['alternatives'] as Array<any>).map(FoodAlternativeFromJSON)),
    };
}

export function SuggestFoodAlternativesResponseToJSON(json: any): SuggestFoodAlternativesResponse {
    return SuggestFoodAlternativesResponseToJSONTyped(json, false);
}

export function SuggestFoodAlternativesResponseToJSONTyped(value?: SuggestFoodAlternativesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'alternatives': ((value['alternatives'] as Array<any>).map(FoodAlternativeToJSON)),
    };
}
