/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **What you can build** - **Scan food** — detect foods and nutrition from a meal photo or a plain-English description, and correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DietPreference } from './DietPreference.js';
import {
    DietPreferenceFromJSON,
    DietPreferenceFromJSONTyped,
    DietPreferenceToJSON,
    DietPreferenceToJSONTyped,
} from './DietPreference.js';
import type { DietRestriction } from './DietRestriction.js';
import {
    DietRestrictionFromJSON,
    DietRestrictionFromJSONTyped,
    DietRestrictionToJSON,
    DietRestrictionToJSONTyped,
} from './DietRestriction.js';

/**
 *
 * @export
 * @interface SuggestFoodAlternativesBody
 */
export interface SuggestFoodAlternativesBody {
    /**
     * Allergens/ingredients to avoid. Omit it (or send []) if none apply.
     * @type {Array<DietRestriction>}
     * @memberof SuggestFoodAlternativesBody
     */
    dietRestrictions?: Array<DietRestriction>;
    /**
     * Dietary patterns to match. Omit it (or send []) if none apply.
     * @type {Array<DietPreference>}
     * @memberof SuggestFoodAlternativesBody
     */
    dietPreferences?: Array<DietPreference>;
}

/**
 * Check if a given object implements the SuggestFoodAlternativesBody interface.
 */
export function instanceOfSuggestFoodAlternativesBody(value: object): value is SuggestFoodAlternativesBody {
    return true;
}

export function SuggestFoodAlternativesBodyFromJSON(json: any): SuggestFoodAlternativesBody {
    return SuggestFoodAlternativesBodyFromJSONTyped(json, false);
}

export function SuggestFoodAlternativesBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestFoodAlternativesBody {
    if (json == null) {
        return json;
    }
    return {

        'dietRestrictions': json['diet_restrictions'] == null ? undefined : ((json['diet_restrictions'] as Array<any>).map(DietRestrictionFromJSON)),
        'dietPreferences': json['diet_preferences'] == null ? undefined : ((json['diet_preferences'] as Array<any>).map(DietPreferenceFromJSON)),
    };
}

export function SuggestFoodAlternativesBodyToJSON(json: any): SuggestFoodAlternativesBody {
    return SuggestFoodAlternativesBodyToJSONTyped(json, false);
}

export function SuggestFoodAlternativesBodyToJSONTyped(value?: SuggestFoodAlternativesBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'diet_restrictions': value['dietRestrictions'] == null ? undefined : ((value['dietRestrictions'] as Array<any>).map(DietRestrictionToJSON)),
        'diet_preferences': value['dietPreferences'] == null ? undefined : ((value['dietPreferences'] as Array<any>).map(DietPreferenceToJSON)),
    };
}
