/* tslint:disable */
/* eslint-disable */
/**
 * January AI Partner API
 * Build food and metabolic intelligence into your product with the January API — one API for understanding what people eat and how food may affect them.  Use it to **search foods** by name, barcode, natural language, restaurant, or menu item; **scan meals from photos** and correct the results in plain English; **log food** and retrieve a user\'s history; **recommend healthier alternatives**; and **predict glucose response** to a meal — no sensor required.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: umer@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FoodLogInputFood } from './FoodLogInputFood.js';
import {
    FoodLogInputFoodFromJSON,
    FoodLogInputFoodFromJSONTyped,
    FoodLogInputFoodToJSON,
    FoodLogInputFoodToJSONTyped,
} from './FoodLogInputFood.js';

/**
 *
 * @export
 * @interface UpdateFoodLogBody
 */
export interface UpdateFoodLogBody {
    /**
     *
     * @type {Array<FoodLogInputFood>}
     * @memberof UpdateFoodLogBody
     */
    foods?: Array<FoodLogInputFood>;
    /**
     * UTC consumption time, ending in Z.
     * @type {string}
     * @memberof UpdateFoodLogBody
     */
    timestampUtc?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateFoodLogBody
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateFoodLogBody interface.
 */
export function instanceOfUpdateFoodLogBody(value: object): value is UpdateFoodLogBody {
    return true;
}

export function UpdateFoodLogBodyFromJSON(json: any): UpdateFoodLogBody {
    return UpdateFoodLogBodyFromJSONTyped(json, false);
}

export function UpdateFoodLogBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFoodLogBody {
    if (json == null) {
        return json;
    }
    return {

        'foods': json['foods'] == null ? undefined : ((json['foods'] as Array<any>).map(FoodLogInputFoodFromJSON)),
        'timestampUtc': json['timestamp_utc'] == null ? undefined : json['timestamp_utc'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateFoodLogBodyToJSON(json: any): UpdateFoodLogBody {
    return UpdateFoodLogBodyToJSONTyped(json, false);
}

export function UpdateFoodLogBodyToJSONTyped(value?: UpdateFoodLogBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'foods': value['foods'] == null ? undefined : ((value['foods'] as Array<any>).map(FoodLogInputFoodToJSON)),
        'timestamp_utc': value['timestampUtc'],
        'name': value['name'],
    };
}
