/* tslint:disable */
/* eslint-disable */
/**
 * January AI - Nutrition Intelligence APIs
 * Build food and metabolic intelligence into your product — one API for understanding what people eat and how food may affect them.  **Clinical-grade precision, consumer-grade experiences.** January builds the infrastructure underneath the product: turning messy health and nutrition data into reliable intelligence, so your team spends its time on the experience instead of the foundation.  **What you can build** - **Scan food** — detect foods and nutrition from a meal photo or a plain-English description, and correct results conversationally - **Search the food database** — by name or barcode — and get healthier alternatives for any food - **Log food** — a per-user diary with day-range queries - **Predict glucose response** to any meal — no sensor required  **Getting started** 1. Create an API key in the [Developer Dashboard](https://dashboard.january.ai) — the full key is shown once, at creation. 2. Send it as `Authorization: Bearer <your key>` — click **Authorize** here to make every example below a live request. 3. Identify your end user with the `x-end-user-id` header wherever a request acts on their data.  **Support** — [support@january.ai](mailto:support@january.ai) · [Discord community](https://discord.gg/cYQeh3UnC) · [docs.january.ai](https://docs.january.ai)
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@january.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const WeightUnit = {
    lb: 'lb',
    kg: 'kg',
    unknownDefaultOpenApi: '11184809'
} as const;
export type WeightUnit = typeof WeightUnit[keyof typeof WeightUnit];


export function instanceOfWeightUnit(value: any): boolean {
    for (const key in WeightUnit) {
        if (Object.prototype.hasOwnProperty.call(WeightUnit, key)) {
            if (WeightUnit[key as keyof typeof WeightUnit] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WeightUnitFromJSON(json: any): WeightUnit {
    return WeightUnitFromJSONTyped(json, false);
}

export function WeightUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeightUnit {
    return json as WeightUnit;
}

export function WeightUnitToJSON(value?: WeightUnit | null): any {
    return value as any;
}

export function WeightUnitToJSONTyped(value: any, ignoreDiscriminator: boolean): WeightUnit {
    return value as WeightUnit;
}
